### ISSUE TITLE
https://tuoitre.vn/  wrongly block section of page

### ISSUE THREAD

**Issue by mrxyzl** [easylist/easylist#10171]
### List the website(s) you're having issues:

https://tuoitre.vn/
### What happens?

The Megastory section of the page is block, but the megastory text still remain and wrongly placed
### List Subscriptions you're using:

Easy list
### Your settings
Running Vivaldi on android, but this also happens on firefox mobile

- OS/version: Andeoid 12
- Browser/version: Vivaldi and Firefox mobile
- Adblock Extension/version: ublock and built in adblock from vivaldi

**Comment by ryanbr** [comment]
Screenshot of the issue, does it occur on desktop?

**Comment by mrxyzl** [comment]
> Screenshot of the issue, does it occur on desktop?

![Uploading Screenshot_20211222-184020_Vivaldi Browser Snapshot.jpg…]()
![Uploading Screenshot_20211222-184048_Vivaldi Browser Snapshot.jpg…]()

**Comment by mrxyzl** [comment]
> Screenshot of the issue, does it occur on desktop?

I updated the screenshot.
The first one show the megastory leftiver letter in wrong place

The second one show how the page look when adblock disabled

**Comment by ryanbr** [comment]
Without knowing what to look for, Not much I can do.  What I'm seeing, and it looks fine.
![two](https://user-images.githubusercontent.com/1659004/147179274-cff9100a-951d-4976-9b9b-a3626007a222.png)

**Comment by mrxyzl** [comment]
> Without knowing what to look for, Not much I can do. What I'm seeing, and it looks fine. ![two](https://user-images.githubusercontent.com/1659004/147179274-cff9100a-951d-4976-9b9b-a3626007a222.png)

I forget to mention that this happens  on mobile only

**Comment by stephenhawk8054** [comment]
@ryanbr It only happens on mobile, since it's hard to test on mobile, I tested with user agent changed to android on Firefox PC, and I can still reproduce it.

My test configuration: EL + EP + ABPVN (ublock 1.39.2) with Enhanced Tracking Protection turned off on Firefox.

I think the problem is in `.admicro.` filter, the page looks like this when blocking it

<details><summary>Issue screenshot</summary>

![2](https://user-images.githubusercontent.com/66517106/147189222-16209881-60d5-4f99-8df9-dbd88626cc5b.png)

</details>

<details><summary>Expected screenshot</summary>

![5](https://user-images.githubusercontent.com/66517106/147189310-f990d16b-7d48-40bd-88f7-762c23da1b4a.png)

</details>

After I allow these scripts, the page looks normal again

`@@||media1.admicro.vn/cms/*$script,domain=tuoitre.vn`

However, sometimes it still has issues after refreshing, which is unstable. After I allow this frame, it becomes more stable

`@@||quangcao.tuoitre.vn/customer/banner/*$subdocument`

but with this one, I think I should cc @hoang-rio.

**Comment by hoang-rio** [comment]
@stephenhawk8054 I tried your propose rule but in seem did not work
```
@@||quangcao.tuoitre.vn/customer/banner/*$subdocument
@@||media1.admicro.vn/cms/*$script,domain=tuoitre.vn
```
I will find another rule that can fix this issue

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 I tried your propose rule but in seem did not work
> 
> ```
> @@||quangcao.tuoitre.vn/customer/banner/*$subdocument
> @@||media1.admicro.vn/cms/*$script,domain=tuoitre.vn
> ```
> 
> I will find another rule that can fix this issue

Have you turned off Firefox's built in tracking protection?

**Comment by hoang-rio** [comment]
> > @stephenhawk8054 I tried your propose rule but in seem did not work
> > ```
> > @@||quangcao.tuoitre.vn/customer/banner/*$subdocument
> > @@||media1.admicro.vn/cms/*$script,domain=tuoitre.vn
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I will find another rule that can fix this issue
> 
> Have you turned off Firefox's built-in tracking protection? I just tested on a brand new Firefox profile on android and it worked. Turning on built-in one causes the problem immediately.

Ok I will try to turn off Firefox's build-in tracking protection

**Comment by hoang-rio** [comment]
@ryanbr I think this issue should be close.

**Comment by mrxyzl** [comment]
> @ryanbr I think this issue should be close.

After the fix theres now empty poace holder here and there in the news article page

Can you implement  an cosmetic  filter? 
![Screenshot_20211228-202639_Vivaldi Browser Snapshot](https://user-images.githubusercontent.com/91355555/147570990-d1ae8477-3faf-4b6b-9b7c-f1052e52c081.jpg)

**Comment by hoang-rio** [comment]
Finaly it OK for both case

**Comment by stephenhawk8054** [comment]
> Finaly it OK for both case

Yup, I confirm it's fixed now 👍
