### ISSUE TITLE
Cosmetic Filters needed for Carbuzz.com

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#10661]
### List the website(s) you're having issues:

`https://carbuzz.com/news/man-sues-mercedes-after-door-ripped-his-thumb-off`

### What happens?

Needs cosmetic filters for ad placeholders.

### Your settings

- OS/version: 
- Browser/version: 
- Adblock Extension/version:

**Comment by THEtomaso** [comment]
The placeholders are shown because of the following rule, found in '**uBlock filters**':
`@@||carbuzz.com^$ghide`

Therefore, you should report the issue here:
https://github.com/uBlockOrigin/uAssets/issues/

..like pointed out by ryanbr here:
https://github.com/easylist/easylist/issues/10735#issuecomment-1030726661
