### ISSUE TITLE
Issue with /services/analytics/* pattern

### ISSUE THREAD

**Issue by alphabetek** [easylist/easylist#1081]
### List the website(s) you're having issues:

Not released yet, issue discovered in QA stage.
The issue will be faced by end users and has been discovered by QA people in QA stage. It is a preventive approach.

### Describe the issue

We have some URLs containing <custom_path>/services/analytics/<custom_path>,
/services/analytics/* seems to be a very generic pattern and could be used by any organization.

### Screenshot(s)

![services-analytics](https://user-images.githubusercontent.com/5899023/39123459-3cea39bc-46f8-11e8-9d9a-88974f4538dc.png)

### Versions

- Browser/version: Chrome and FF
- uBlock Origin version: 1.16.0

### Notes

Line to be removed: https://github.com/easylist/easylist/blob/d0a67e61ee7ba1f066f11070babf13fac035e716/easyprivacy/easyprivacy_general.txt#L2629

**Comment by Khrin** [comment]
Really no chances to have an example link now?

**Comment by alphabetek** [comment]
@Khrin I am afraid for now really no chances, I will have a working scenario in a week that you can test.

**Comment by mitosch** [comment]
Here we go:

Not-blocked example:
A simple index.html page with a cat image: http://tmp.mitos.ch/
Result: cat.png is shown because the URL is: http://tmp.mitos.ch/cat.png

Blocked example:
A simple index.html page with a cat image with an URL /services/analytics/: http://tmp.mitos.ch/services/analytics/
Result: cat.png is now blocked because the URL is: http://tmp.mitos.ch/services/analytics/cat.png

**Comment by alphabetek** [comment]
@Khrin please check #1109
