### ISSUE TITLE
material.angular.io

### ISSUE THREAD

**Issue by aphedges** [easylist/easylist#10841]
### List the website(s) you're having issues:

`https://v12.material.angular.io/components/select/overview#multiple-selection`

### What happens?

The multiple select dropdown from Angular Material can no longer be closed.

### List Subscriptions you're using:

EasyList, EasyPrivacy, AdGuard Annoyances, AdGuard Social Media, Fanboy's Annoyance

### Your settings

- OS/version: macOS 11.6.3 x86_64
- Browser/version: Firefox 97.0
- Adblock Extension/version: uBlock Origin 1.41.2

### Other details:

I specifically discovered this on my own site, but I cannot share the URL because the site is supposed to stay private for institutional reasons. However, I could reproduce it on the Angular Material site itself, so hopefully my specific site isn't needed. I can try to make a minimal reproduction of the issue, but I assume you don't want to build and run an Angular site on your machine just to work on this.

By using uBlock Origin's logger, I was able to see that the rule `##.cdk-overlay-container > .cdk-overlay-backdrop` in Fanboy's Annoyance is causing the breakage. I was able to confirm this by disabling Fanboy's Annoyance to get the dropdown to work again and by manually adding the rule to my filters to break it again.

It is difficult to properly demonstrate on `material.angular.io` itself anymore because the recent commit https://github.com/easylist/easylist/commit/52f8629dc8040896907fb8c17dd67f4dd08b0f84 disables some rules on the site. I was able to use the site for testing this bug until I updated all my filters, which I did to verify it wasn't caused by an out-of-date filter.

The bug is specifically caused by https://github.com/easylist/easylist/commit/83f04bbe70fc740245518d3a6da568f6f749521c and https://github.com/easylist/easylist/commit/1f80432e352b48b80663ed962eec3563f7bf8af3.

Someone recently made the PR https://github.com/easylist/easylist/pull/10683 that would fix this, but the conversation on the issue https://github.com/easylist/easylist/issues/10623 implies the fix is overly broad.

**Comment by ryanbr** [comment]
So its resolved by https://github.com/easylist/easylist/commit/52f8629dc8040896907fb8c17dd67f4dd08b0f84 .

**Comment by PowerKiKi** [comment]
@ryanbr the commit you mentioned seems to be missing the point that the original filter is too wide because it targets a library, instead of a specific usage of that library on a specific site. And that library is used for thousands of legit uses that have nothing to do with advertisement or otherwise annoying behaviors.

There are at the [**very minimum** 41,085 sites](https://trends.builtwith.com/framework/Angular-Material) that use it, but more realistically there are more than 83,589 of them. It does not seem reasonable to list all those good behaving sites.

The same as you would not break all sites that use jQuery or React, you should not break all sites that use Angular Material.

I recommend merging  #10683 to un-break all sites, and then adding the the very few sites that are considered malicious with a more specific rule.

**Comment by PowerKiKi** [comment]
There's been a very similar case 2 years ago where the too wide filter was indeed reverted: https://github.com/easylist/easylist/pull/4869

**Comment by aphedges** [comment]
@ryanbr, while technically the issues with `material.angular.io` are solved by <https://github.com/easylist/easylist/commit/52f8629dc8040896907fb8c17dd67f4dd08b0f84>, as @PowerKiKi and I have pointed out, the problem isn't that this specific site has broken as much as everyone using the Angular Material framework has likely been affected.

**Comment by ryanbr** [comment]
Was resolved

**Comment by aphedges** [comment]
I can confirm the problematic filter was removed by 5940ebe9b4f0ac8cdcc71adec28dbf0290a38930.
