### ISSUE TITLE
https://nytimes.com/ video content blocked

### ISSUE THREAD

**Issue by rgov** [easylist/easylist#1174]
### List the website(s) you're having issues:

* `https://www.nytimes.com/2018/05/18/us/dimitrios-pagourtzis-gunman-texas-shooting.html`

### What happens?

The embedded video does not load, and I just see a spinner indefinitely.

### List Subscriptions you're using:

* EasyList

### Your settings

- OS/version: macOS 10.13.4
- Browser/version: Safari 11.1
- Adblock Extension/version: uBlock Origin for Safari 1.16.0

**Comment by Khrin** [comment]
Works fine for me. Do you use exclusively EasyList?

**Comment by THEtomaso** [comment]
It's not a **EasyList** issue.
The site has a cookie consent popup, which needs to be accepted in order to play videos.

When troubleshooting this on my own system, I found several filters which blocked it:
1: **My own personal filter**: `nytimes.com/graphql/v2`
2: **Fanboy's Annoyance List** and **Fanboy's Cookie List**: `nytimes.com##.expanded`
3: **I don't care about cookies**: `nytimes.com##.shown.expanded`

Fixes for the rules above:
`@@nytimes.com/graphql/v2`
`nytimes.com#@#.expanded`
`nytimes.com#@#.shown.expanded`

Note:
The page needs to be refreshed, after having accepted the cookie consent (site issue).

(PS: I've reported the issue to the respective filter authors)

**Comment by THEtomaso** [comment]
Turns out that the exceptions that I mentioned in my previous post aren't needed after all:
https://github.com/ryanbr/fanboy-adblock/issues/483/
:)

**Comment by THEtomaso** [comment]
No, like I said; none of those exceptions are needed.
I think the OP might have been confused by the same thing that I was..
The fact that the videos shows as black frames, simply gives you the impression that they failed to load, although they play just fine when clicking on them!

To be honest, I can't remember why I've created that specific block rule for my personal filter ( `nytimes.com/graphql/v2` )
Right now, I can't figure out what it does exactly, but I'm sure that I've must have thought it was a good idea at some point, so I'll just leave it in there for now. :)

**Comment by rgov** [comment]
For me the news feed on https://www.nytimes.com/ (under the crossword puzzle link) also fails, is it related?

**Comment by ryanbr** [comment]
okay, that was more testable. made it more specific; https://github.com/easylist/easylist/commit/9b13f21e2d1de05b642468989b1902dfa7848341

**Comment by ryanbr** [comment]
alternatively this could be tried; if the above filter is still problematic.

`nytimes.com##div > .expanded.shown`
or
`nytimes.com##div > div > .expanded.shown`

**Comment by ryanbr** [comment]
Closing, seems fine now
