### ISSUE TITLE
mtvuutiset.fi

### ISSUE THREAD

**Issue by Nojuuu** [easylist/easylist#12856]
### List the website(s) you're having issues:

`https://www.mtvuutiset.fi/artikkeli/meita-hamattiin-jari-matti-latvala-esitti-teoriansa-suomen-mm-rallin-jalkeen/8483964`

### What happens?

Tracking 

![image](https://user-images.githubusercontent.com/84513173/183457749-09602955-d515-4a35-b946-2afd4f152001.png)

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 103.0.1
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

Might need to accept cookies and interact with this to make it show up in logger:

![image](https://user-images.githubusercontent.com/84513173/183458301-5ffa02b1-df25-43aa-bc4c-569f3661ddba.png)

**Comment by peace2000** [comment]
`leadfamly.com` seems to be a tracking / analytics domain.

`https://leadfamly.com/`

Used in many sites: https://publicwww.com/websites/%22leadfamly.com%22/
e.g.: `https://landbrugsavisen.dk/`

**Comment by dannieleadfamly** [comment]
@peace2000 Writing on behalf of Leadfamly. Leadfamly is a marketing platform that is used to engange users using gamification. Part of what we offer is tracking our campaigns to understand who visits, how long they spend etc. Would it be possible for you to narrow down this restriction so that our content, which is not tracking / ads will show? We have of course no issue with actual tracking & ads domains to continue being on the blacklist.

The domains that we do have which contain tracking or could be considered ads are:

1. analytics-zone-1.api.leadfamly.com = Internal analytical service for tracking usage.
2. popup.leadfamly.com = Popup platform that our clients use to enable popups on their website for various things.

With the 2 above blocked.

**Comment by peace2000** [comment]
I don't have a write access here, but if there are any incorrect blocking, please file an issue report here with samples: https://github.com/easylist/easylist/issues and Easylist maintainers will check it.
