### ISSUE TITLE
Alter or remove Koko Analytics filter

### ISSUE THREAD

**Issue by dannyvankooten** [easylist/easylist#12973]
Hello,

000296b3f67137aee4b86c8d739e52670e21b6d6 / #12864 added a filter to block all requests containing `koko-analytics`, with the aim of disabling analytics tracking by websites that run the [Koko Analytics plugin for WordPress](https://www.kokoanalytics.com/), of which I am the author.

While it could be argued that this plugin should not be blocked by EasyPrivacy as it does not track users in any way, it just counts visits and views to certain URL's, does not store anything visitor related (it wouldn't scale at all if it did), instead I would like to propose to change the filter so it only  blocks the tracking script.

My reason for this is that I have been getting a lot of questions from plugin users which are also running an ad-blocker, asking me why their dashboard suddenly broke. It's because EasyPrivacy is blocking the request to the JavaScript file which spins up the application showing their statistics in their website backend (WP Admin). 

I would really like to have my plugin working for users with an ad-blocker enabled without them having to whitelist their own domains because every user that is using Koko Analytics instead of Google Analytics or what have you is a win for the internet, imo. 

I'll add a PR which addresses this shortly hereafter.

Thank you for your consideration!

**Comment by dannyvankooten** [comment]
You can view this issue in action but also what Koko Analytics is tracking / showing by visiting the demo dashboard for kokoanalytics.com here, by the way: https://www.kokoanalytics.com/?go-to-demo

(Disable your ad-blocker if you see a blank page, in case that was not clear. :sweat_smile:)

**Comment by dannyvankooten** [comment]
Thank you for looking into this @ryanbr, but 81d0220498533535c360c5d0e16f7b17852800e6 doesn't really work because Koko Analytics is a WordPress plugin which people install on their own websites (domains). The dashboard on kokoanalytics.com is just an example, but it could live on any domain. 

The proper fix would be to only block the tracking script and not any file that lives in a subdirectory called `koko-analytics`.

**Comment by arnelap** [comment]
If you want to block just the tracking script as Danny suggested, and allow the backend of Koko to keep working for those using Easyist, the correct script to block is: **/koko-analytics-collect.php**

Thanks!!


<rant>
Please note that Koko doesn't infringe on end user privacy in any way.

Koko doesn't track individual users in any way, all it does is count the total amount of visits to a Wordpress post or page. It does not keep track of IP addresses and doesn't assign any ID to individual users. 

The database behind Koko is literally a list of page/post IDs and the total number of visits counted for that page per day. That's it.

It doesn't send any data off-site, everything is handled on the Wordpress site  that has the plugin installed, no data is shared to Kokoanalytics.com or anywhere else. 

Koko also respects the "do not track" setting you can set in your browser. 

As Koko is a very privacy-conscious analytics solution I think it's worth considering to not block it at all, as more people using privacy respecting analytics improves end user privacy  and thus fits in the spirit of Easylist. Therefore it should be the goal of Easylist to have more people use Koko analytics instead of the big bad analytics company.
</rant>
