### ISSUE TITLE
ads2ads.net

### ISSUE THREAD

**Issue by FahrutdinovOF** [easylist/easylist#13660]
`##.default-creative-container`

A: https://linuxhint.com/find-last-modified-files-in-linux/ or  https://www.piloteers.org/threads/automatic-auto-idle-stop-system-set-to-off-by-default-ver-3-detailed.164718/ 

![image](https://user-images.githubusercontent.com/20794426/194519277-648ea484-f5ef-4efc-908c-a083bdc04371.png)

**Comment by smed79** [comment]
I can't reproduce, no ads for me.

Please test below filters
```
/display-ads.
||ads2ads.net^$third-party
```

**Comment by FahrutdinovOF** [comment]
Thank you!
Filter not work.

This ad is inserted by google (Auto ads).
![image](https://user-images.githubusercontent.com/20794426/194716487-b4fffadf-7290-49eb-a5b8-0b7144742acf.png)
Opened container
![image](https://user-images.githubusercontent.com/20794426/194716552-5d8ac986-5169-4137-9a04-8ebb17334af7.png)
After the page is loaded, banners are loaded
![image](https://user-images.githubusercontent.com/20794426/194716763-c2e6d60b-cc3b-4d78-8871-548b4d4bd5ce.png)

**Comment by spirillen** [comment]
Just kill the entire domain (script)

```css
||http://ads2ads.net/^
```

![image](https://user-images.githubusercontent.com/44526987/194970968-5e4e505a-7c1a-4d1d-a8ca-3dc1045f17d9.png)

<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/3472508

</details>

**Comment by smed79** [comment]
@spirillen It's not about blocking the whole domain to solve the problem here because the ad shown in the screenshot should already be handled by the easylist filter. So this is most likely an adblock circumvention mechanism.

@FahrutdinovOF Report an ABP issue via the [Issue reporter](https://help.eyeo.com/en/adblockplus/report-an-issue) and post the link here.
