### ISSUE TITLE
fanboy_newsletter_specific_uBO.txt is missing in Fanboy's Annoyance List for uBO

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#14487]
I noticed that this fix (which was added two days ago) didn't appear in Fanboy's Annoyance List for uBO:
https://github.com/easylist/easylist/commit/efbfdc030e4ba821cbfc98b53372ad16e6af893e#diff-b69d6ed5f0dac55800826f353a2edbffd73cf41f4d1e17e8677e79743449be41

Seems that `!#include fanboy_newsletter_specific_uBO.txt` is missing!?

**Comment by DandelionSprout** [comment]
From what I currently understand (but don't take my word for it), there are ongoing issues with both the `easylist-downloads.adblockplus.org` and `secure.fanboy.co.nz` hostings of Fanboy's Notifications Blocking List. The former apparently couldn't handle any `!#include` files at all without breaking in uBO, while the latter was 3½ months outdated.

**Comment by DandelionSprout** [comment]
Although I know of ongoing problems with `!#include` in Fanboy's Notifications Blocking List's `easylist-downloads.adblockplus.org` hosting, I think the Annoyances list's newsletter stuff has been fixed by now: 
![image](https://user-images.githubusercontent.com/22780683/209477457-c2eb320f-644c-4c00-827e-b78464d450d5.png)
