### ISSUE TITLE
Please add guildeducation.com domain to Optimizely in the easyprivacy_allowlist

### ISSUE THREAD

**Issue by dariawhitecastle** [easylist/easylist#14930]
### List the website(s) you're having issues:

`https://*.guildeducation.com`
`https://optimizely.guildeducation.com/*`
`https://*.guildeducation.com/optimizelydatafile=*`
`https://cdn.optimizely.com/datafiles/* with referrer from https://*.guildeducation.com`

### What happens?

If users have the EasyPrivacy list enabled in their adblocking extensions, then they cannot load our feature flags and a/b tests. The effect is different across our product, such as missing new functionality, new styles, or new versions of existing capabilities. This is especially problematic when we expect all users of a customer to have access to a capability they have paid for.

### List Subscriptions you're using:

EasyPrivacy

### Your settings

- OS/version: Ventura 13.1
- Browser/version: Chrome v.109
- Adblock Extension/version: v.5.4

### Other details:

Our company’s product, offered through [guildeducation.com](http://guildeducation.com/) does not serve any types of ads or ad-related materials. We are an education benefit provider, helping connect our users to deb-free education. We do use Optimizely for product management best practices of testing new offerings for our users.

The edit can be made on Line 76 in [easyprivacy_allowlist file](https://github.com/easylist/easylist/blob/79dd21808d4cf2ef04def6501753d017c57dca76/easyprivacy/easyprivacy_allowlist.txt)

**Comment by ryanbr** [comment]
No thank you. Need more than this to be added to the lists. Removing the Optimizely requirement on your end would be easier also.

**Comment by jacobmclocklin** [comment]
@ryanbr Thank you for the response! I'm on the engineering team with @dariawhitecastle. To add more specifics to our request: 
Optimizely is essential for us coordinating the release of few functionality across many separate repositories. For example, as we launch our rebranded experience, referencing one feature flag across 25 repositories is a more effective strategy than coordinating the deployment of changes across the 25 repos. For users who are inadvertently blocking our use of optimizely for this, they will experience the rebrand in pieces as each repo removes the use of the Optimizely flag. The same was true for releasing new features like student debt loan payment support and career resources. 
Overall, with Optimizely blocked, users will have an inconsistent and confusing experience where changes and functionality are sporadically updated throughout a lengthy disruption period before repos are in sync in production.
Otherwise, what else should be offered in order to justify the update? Our use of Optimizely is always for the benefit of our users, not their detriment. 
Thank you!
