### ISSUE TITLE
quora.com: garish text ad interferes with text flow

### ISSUE THREAD

**Issue by crystalsphynx** [easylist/easylist#1542]
### List the website(s) you're having issues:

`https://www.quora.com/Is-there-a-way-to-change-Windows-default-font-preview-phrase-from-The-quick-brown-fox-jumps-over-the-lazy-dog`

### What happens?

search topic in duckduckgo or within quora.  text add with hyperlink shown between question and answer.  I am not savvy enough to create filters for randomish divs

### List Subscriptions you're using:

nano adblocker config
https://gist.github.com/crystalsphynx/f513c84ea656780f28c4c061b6ec6653

### Your settings

- OS/version: W10
- Browser/version: iridium 2018.4 (based on Chromium 66.0.3359.130)
- Adblock Extension/version: nano adblocker 1.0.0.53

### Other details:

![quora div abuse unblocked text ad with spammy link](https://user-images.githubusercontent.com/41244545/42729498-182a8b4a-878f-11e8-8253-dd3c1bb71478.png)

**Comment by krystian3w** [comment]
This is should by fixed in uBlock Origin filters List.

https://github.com/uBlockOrigin/uAssets/issues/2404

* https://github.com/uBlockOrigin/uAssets/commit/3c382dd85ef80979b967191cd0d453db0655980c
* https://github.com/uBlockOrigin/uAssets/commit/9717329fb2275d93d2e1c87142db9a8202360798
* https://github.com/uBlockOrigin/uAssets/commit/5eff447a36774725cffc428ada8acd093f90fbe8
* https://github.com/uBlockOrigin/uAssets/commit/5eff447a36774725cffc428ada8acd093f90fbe8
* https://github.com/uBlockOrigin/uAssets/commit/8f42fafd9287e8041559ca4d127903afd18a6149
* https://github.com/uBlockOrigin/uAssets/commit/2e4d2edfbda9c19065b5eefdff2bfcd9e49230a5

Pruge all lists, Update all and try again. 
Can you update Nano Adblocker to 1.00.55 / 1.0.0.56 version too.

**Comment by krystian3w** [comment]
`##.grid_page > .layout_2col_main >  div[id] > div[class]` - PC
`##div[id^="__"]:-abp-has(.advertiser_endpoint)` - Mobile

**Comment by crystalsphynx** [comment]
> Can you update Nano Adblocker to 1.00.55 / 1.0.0.56 version too.

That's odd the update is in progress but hanged.  After homework I will backup, remove, and reinstall.

**Comment by peace2000** [comment]
This seems to be fixed now as I don't see ads anymore. @Khrin
