### ISSUE TITLE
YouTube broken again (Fanboy's Annoyance List) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#15599]
I'm dropping to file a thorough report this time, since the issue have been discussed in great detail, many times in the past.

In short, this rule (in **Fanboy's Annoyance List**) now breaks the cookie consent popup @ `https://www.youtube.com` again!:
`youtube.com##tp-yt-paper-dialog[style-target="host"][role="dialog"]`

As I'm sure everyone is aware of at this point, YouTube's cookie popup needs to be allowed, in order to avoid weird behaviour!

**Comment by ryanbr** [comment]
Removed, have a better suggestion to remove the Youtube TV nag? @THEtomaso 

![screenshot_2023-04-18_at_16 54 58](https://user-images.githubusercontent.com/1659004/233203253-fd0e38b9-3cf5-4485-8d29-b6c0d21a38d6.png)

**Comment by THEtomaso** [comment]
> have a better suggestion to remove the Youtube TV nag?

Unfortunately, no.
After a bunch of tries and fails, everyone gave up on it.
uBO filters, AdGuard, IDCAC, etc. all allows that popup, in order to avoid issues.

**Comment by krystian3w** [comment]
If we plans support legacy browser without support `:not` then also now works:

```adb
youtube.com##tp-yt-paper-dialog[style-target="host"][role="dialog"][modern]
! due cookie modal is "oldie"
```

**Comment by ryanbr** [comment]
`youtube.com##tp-yt-paper-dialog[style-target="host"][role="dialog"][style*="z-index"]`

causes no issues then?

**Comment by krystian3w** [comment]
It certainly allows you to close the cookie policy manually so that the video does not immediately stop when you click (or glitched autoplay playlists/start on specific second).

---

To check for logged in in total is left to manage the subscription from the "bell" (as it continues to be a pop-up), the pop-up of deleting the comment (if still exist).

I haven't checked to see if there's a truncated share button - it, too, generates a pop-up with an option to indicate the exact second of the video (I prefer cut only the social media buttons in there pop-up - admiring the mercy of the html code button and the link generator with the exact second).

Other friendly pop-ups I do not associate.
