### ISSUE TITLE
Google's new ad servers with `cn`

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylist#15643]
In privacy-protection-tools/anti-AD#781, we found many google ad domains with `-cn` suffix. (These domain are recorded in the Chinese regulator under a Google company, so they do belong to Google)

I just compared them with [easyprivacy+easylist list](https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt)

```
! New domains
2mdn-cn.net
admob-cn.com
doubleclick-cn.net
googleadservices-cn.com
google-analytics-cn.com
googleoptimize-cn.com
googletagmanager-cn.com
googletagservices-cn.com
```

The domains above have exact prototypes in easyprivacy+easylist,

```AdBlock
! Existing rules
||2mdn.net^
||admob.com^
||doubleclick.net^
||googleadservices.com^$third-party
||google-analytics.com^$third-party
||googleoptimize.com^
||googletagmanager.com^
||googletagservices.com^
```

And 3 domains contain obvious keywords:

```
! New domains
googleads-cn.com
googleadsserving.cn
googlevads-cn.com
```

Also, there is `googlesyndication-cn.com`, and `googlesyndication.com` is partly blocked in EasyList.

----

We have only found few dns records so far, no other evidence now.

Some of these domains may be added into EasyPrivacy. For others, do I need to report them to EasyList China?

**Comment by ryanbr** [comment]
Given its google, it'll be worth adding here.

**Comment by spirillen** [comment]
I know this issue is closed, but yet to share a bit of knowledge

The following is a list of google Ads- tracking domains in/for China

- 2mdn-cn.net https://github.com/mypdns/matrix/issues/38850
- admob-cn.com https://github.com/mypdns/matrix/issues/39958
- doubleclick-cn.net https://github.com/mypdns/matrix/issues/39966
- google-analytics-cn.com https://github.com/mypdns/matrix/issues/39970
- googleads-cn.com https://github.com/mypdns/matrix/issues/40411
- googleadservices-cn.com https://github.com/mypdns/matrix/issues/40444
- googleadsserving.cn https://github.com/mypdns/matrix/issues/40450
- googleoptimize-cn.com https://github.com/mypdns/matrix/issues/40466
- googletagmanager-cn.com https://github.com/mypdns/matrix/issues/40491
- googletagservices-cn.com https://github.com/mypdns/matrix/issues/40505
- googlevads-cn.com https://github.com/mypdns/matrix/issues/40524
