### ISSUE TITLE
skysports.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#16688]
List the website(s) you're having issues with:

skysports.com

**Comment by Daxy7** [comment]
though the cookie message appears after right?
```
cdn.privacy-mgmt.com
```
what it's supposed to hide, 

```
    ###sp_message_iframe_758392
    ###sp_message_container_758392
```
but we need html/style/body etc overflow filters after adding that popup hider. but we need it to not pop out at us as cosmetic filters are slow, so that's why they done did with a network filter, less resources spent on checking all the html elements.

**Comment by Daxy7** [comment]
@khrin original message was about `/wrapperMessagingWithoutDetection.js` 
in easylist cookies (videos do not play when blocking). invalid if an `@@` filter for that exists already
