### ISSUE TITLE
https://plausible.ripped.guide/ Plausible Analytics Self Hosted

### ISSUE THREAD

**Issue by floppabig1** [easylist/easylist#16928]
This is a self hosted instance of Plausible Analytics and is being used to track visitors to certain websites.

Here is the script which is being used on other websites to track visitors: https://plausible.ripped.guide/js/script.js

**Comment by kekkodance** [comment]
We know this list strives to annihilate all tracking, but as the one who manages ripped.guide's internal tech affairs, i've made sure Plausible is non invasive as a form of analytics.

You probably won't care because it's still analytics, and it's alright if you don't, just know we really need the analytics to know where our traffic comes from and since this is a list that most uBlock Origin users have enabled, we've decided to take measures to keep our analytics working. Individual users can still block them by themselves, but i would much rather not be added to a "list of malicious actors".
