### ISSUE TITLE
https://pasarbokep.com/bokep-indo-ngentot-di-lantai-atas/
https://pasarbokep.com/bokep-indo-memek-sempit-dimasukin-kontol-gede/

### ISSUE THREAD

**Issue by Jokopentil** [easylist/easylist#16922]
![20230802_093553_rmscr.jpg](https://github.com/easylist/easylist/assets/114223791/423dea05-00ff-41f2-b91e-111cfcc80047)

select alternative 1 player and play video pop up in adblocker ultimate

**Comment by Daxy7** [comment]
[NSFW Website] 

use ublock origin and remove adblocker ultimate. they made filters in place to disable the modal popup

**Comment by Daxy7** [comment]
comment on github. not by email. anyway here's what to do
https://github.com/easylist/easylist/assets/91396482/09ceeb65-1ff9-4dda-8997-dec717ef4e75
how to get to it:
https://github.com/gorhill/uBlock/wiki/Dashboard

**Comment by Khrin** [comment]
Please use a different adblocker. Any other good adblocker would do, and don't forget to enable the correct regional list, as in your case.

**Comment by Daxy7** [comment]
![image](https://github.com/easylist/easylist/assets/91396482/866ad0b9-6887-4b14-9e0a-a79bff3fc802)
@Khrin these cosmetics unique to ublock filters.

**Comment by Khrin** [comment]
@Daxy7 I can't check the site at this moment, but I don't see anything "unique" in there, since actually these filters could be added to a regional list anytime and could also be beneficial across every adblocker.

`##.happy-under-player` is very common across several porn sites in different languages.

**Comment by Daxy7** [comment]
they pinned it to `pasarbokep.com` so what i meant was ublock's filters may fix something, timed popup perhaps by cookie?

edit: never mind, these are general filters. my mistake

**Comment by Jokopentil** [comment]
So what filtr macth with adbloker ultimate

**Comment by Daxy7** [comment]
```
what filters does adblocker ultimate use
```

https://adblockultimate.net/filters

though i'd be advised of any bugs since Spotify stopped working after 3 songs when i overlayed adguard and easylist.

you can download from here and import each to your ubo custom filter lists.
language filters already exist in the image I posted [under annoyances]. no need to add from the website individually.

**Comment by Jokopentil** [comment]
Oke thanks👍
