### ISSUE TITLE
(Fanboy Social) appdate.lk

### ISSUE THREAD

**Issue by yokoffing** [easylist/easylist#16975]
#### List the website(s) you're having issues with:
`https://www.appdate.lk/technology/2023-browser-showdown/`

#### What happens?
Twitter button at bottom of article

#### Screenshot(s) 
![twitter at bottom](https://github.com/easylist/easylist/assets/11689349/abca7660-ca9e-4aca-8f55-519ec2f1639d)

**Comment by Sonic5435325** [comment]
Cookie message:
![Screenshot from 2023-08-09 17-38-35](https://github.com/easylist/easylist/assets/89158249/f235e804-5294-44d8-8b06-23f800a2104c)

Back to top button:
`appdate.lk###back-to-top` (Can be fixed in https://github.com/easylist/easylist/pull/16977)

Social button seems to already be hidden with `##.sharrre`.
