### ISSUE TITLE
audiotruyenfull.com in iPhone

### ISSUE THREAD

**Issue by HoangHaiDang02** [easylist/easylist#16991]
#### What happens?
i go to site "audiotruyenfull.com" with device "iPhone" and can't watch content site. After turn off adp content appear.
Problem just appear in device iPhone, iPad(not useragent- i have checked with useragent of iPhone in Chrome browser and can't  reappear.I think the problem is abp core not custom rule because with other abp not appear the problem so pls help me check and fix. Thankiu everyone

when abp enable
![image](https://github.com/easylist/easylist/assets/91521634/d1451c5f-82f3-42a3-af42-c6220d029fb9)
when abp disable
![image](https://github.com/easylist/easylist/assets/91521634/f6932e73-8fd7-4ccb-9a2d-2ed2797e6d72)

#### Filter lists you're using:

EasyList + ABPVN List
#### Your settings:

- OS/version: iPhone 12 iOS 16.4.1
- Browser/version: Cốc Cốc browser
- Adblock extension/version: 3.18

**Comment by Khrin** [comment]
No problems for me with just Easy List.

@hoang-rio Please have a look at it.

**Comment by hoang-rio** [comment]
This issue is reported to ABPVN List (abpvn/abpvn#549) but it's not ABPVN List or any filter list issue. It's only happend in Cốc Cốc browser with custom version of Adblock Plus engine. So I think it's Adblock engine bug not filter list issue.

@HoangHaiDang02 You should report to Cốc Cốc browser iOS develop instead of report to filter list repository

**Comment by HoangHaiDang02** [comment]
it also  appear in safari when i use abp in safari

**Comment by hoang-rio** [comment]
> it also appear in safari when i use abp in safari

It's stil mean issue from Adblock Plus engine for Safari browser core
