### ISSUE TITLE
Block Ping generic rule breaks all third-party loading.

### ISSUE THREAD

**Issue by chaoscalm** [easylist/easylist#17295]
Generic rule inside easyprivacy:

! Block ping
$ping,third-party

Breaks third-party loading on every site using Privacy Browser, had to comment it out.

https://easylist.to/easylist/easyprivacy.txt

Similar problem with the nature of the parser was seen in the past: https://github.com/easylist/easylist/issues/5338

@sorenstoutner

**Comment by sorenstoutner** [comment]
Android's WebView does not differentiate between various types of requests.  Thus `$ping,third-party` turns into `third-party` on WebView, which blocks all third party requests.

For Privacy Browser Android, this entry needs to be removed.  But it shouldn't be considered a bug in EasyPrivacy itself, because this can be appropriately parsed by the majority of systems that use EasyPrivacy, and blocking all third-party HTTP pings is a desirable privacy protection.

A little additional information about limitations in Android's WebView in relation to EasyList can be found at:

https://www.stoutner.com/privacy-browser-android/filter-lists/

**Comment by chaoscalm** [comment]
I understood, I close it now and keep it for reference.

Thank you for the clear explanation.

**Comment by sorenstoutner** [comment]
Note that this is a limitation in Android's WebView that I intend to remove with Privacy WebView in the 4.x series.
