### ISSUE TITLE
www.yahoo.co.jp

### ISSUE THREAD

**Issue by CbumDino** [easylist/easylist#17365]
#### List the website(s) you're having issues with:
https://www.yahoo.co.jp/
(Japanese VPN)

#### What happens?
Widget ads all over the page, it seems the following filter is allowing those banners:
`@@||yads.c.yimg.jp/js/yads-async.js$domain=kobe-np.co.jp|yahoo.co.jp`

#### Screenshot(s) 
![efd07a0c-2237-4f3a-b5e3-9d6c97d9eac0](https://github.com/easylist/easylist/assets/65717387/12f36016-3a85-44e2-8a17-5b8c1be3f80c)

#### Filter lists you're using:
Easylist 

#### Other details:
I would like to understand why the filter above is maintained since overall it's just seems to be related to advertising.

**Comment by Yuki2718** [comment]
Simply because blocking that causes lots of problems, see https://github.com/AdguardTeam/AdguardFilters/issues/84106
You won't see the ad if you block `https://s.yimg.jp/images/listing/tool/yads/ydn/creative/video/ytop_video_bp_pc.min.js` which had been blocked by a recently removed EL rule `/yads/*`. AdGuard Japanese filter blocks this and you can add the rule to ABP's new Japanese filter.
