### ISSUE TITLE
discord.com tracking

### ISSUE THREAD

**Issue by 0o5rlubm** [easylist/easylist#17399]
Discord uses https://discord.com/api/v9/science to track every user action done on the web interface.

This block has been removed from filters in https://github.com/easylist/easylist/commit/c01994f5e9ffb205acf08825984c1e1e17aecfcf due to "Potentially causing images not loading", however I didn't encounter any image loading issue even if I'm blocking this in userfilters since months.

This is also in adguard since months too. https://github.com/AdguardTeam/AdguardFilters/blob/5d1ed89c4876d85c096c8b90af32d76886e1bd5b/SpywareFilter/sections/specific.txt#L1698

Could it be possible to re-consider the addition of this path to the blocklist?

**Comment by ryanbr** [comment]
Not worth being kept adding and removed. lets leave it, not worth the complaints.

**Comment by panty-sniffer** [comment]
I am vouching for this to be reopened and added back. This tracking URL does not serve any purpose. Not keeping this added is a huge privacy risk (collects hundreds of metrics every second, every click _everything_). I have been using this filter (along with adguard tracking filters for vouch) for months without any problems. If anyone still have problem they can simply turn off their ad blocker (there are no other discord filters applied by easyprivacy anyway). Please you cannot ignore this simply because some random report instead of valid legitimate reports from community who actually work and improve the list.

**Comment by thatsprettygood** [comment]
+1
