### ISSUE TITLE
bing.com - burger menu is shown wrongly with "EasyList – Cookie Notices" list

### ISSUE THREAD

**Issue by soredake** [easylist/easylist#18228]
#### List the website(s) you're having issues with:
https://www.bing.com/search?q=Bing+AI&showconv=1&ntref=1

#### What happens?

Burger menu is shown wrongly with "EasyList – Cookie Notices" list

#### Screenshot(s) 
![image](https://github.com/webcompat/web-bugs/assets/5204968/c51238f3-3df1-422a-8807-a337a97661c1)

#### Filter lists you're using:

EasyList – Cookie Notices

#### Your settings:

- OS/version: Windows 11 Pro
- Browser/version: Firefox 121.0
- Ad block extension/version: uBlock Origin 1.55.0

#### Other details:
How it should look:
![image](https://github.com/webcompat/web-bugs/assets/5204968/d4aa2cf2-594f-4295-a82f-7de6a68b168a)

**Comment by THEtomaso** [comment]
It's caused by `##body:style(overflow: auto !important;)`.
Is that currently even needed for `bing.com`?
Disabling that rule with `bing.com#@#body:style(overflow: auto !important;)` fixes the issue for me.

**Comment by soredake** [comment]
Same on https://copilot.microsoft.com/

**Comment by THEtomaso** [comment]
> Same on `https://copilot.microsoft.com/`

I see two problems on that page..

### Issue 1:
The login dialog that is supposed to appear, when pressing the "Sign in" button, is blocked!

### Problem filter:
* **AdGuard Popups filter**
`microsoft.com#$#body { overflow: auto !important; padding-right: 0 !important; }`

### Temp fix:
`microsoft.com#@$#body { overflow: auto !important; padding-right: 0 !important; }`

--

### Issue 2:
Some elements are misaligned (e.g. the M$ logo in the top left corner), due to a blocked cookie consent popup, which needs to be allowed!

### Problem filters:
* **AdGuard Cookie Notices filter**
`copilot.microsoft.com,bing.com#$#.bnp_cookie_banner { display: none !important; }`

* **EasyList - Cookie Notices**
`copilot.microsoft.com##.bnp_cookie_banner`

### Temp fix:
`copilot.microsoft.com#@#.bnp_cookie_banner`

### Note:
Even after allowing and having accepted/rejected the cookie terms, the page still needs to be refreshed for things to show correctly (at least in LibreWolf).

--

@Yuki2718:
Could you look into all these things?

**Comment by THEtomaso** [comment]
> Can you post screenshots?

Sure.

* **Issue 1** (Missing login dialog. Reproducable in LibreWolf/Firefox, but NOT in Chromium-ungoogled).
When pressing the "Sign in" button, only this grey line appears, which I assume is simply a shadow-effect for the missing container:

![filterissue-microsoftcopilot-1](https://github.com/easylist/easylist/assets/9382674/9657c5c1-40bf-47b4-9040-2313f1d03d23)

--

* **Issue 2** (Misalignment of elements. Reproducable in both LibreWolf/Firefox and Chromium-ungoogled):
 
![filterissue-microsoftcopilot-2](https://github.com/easylist/easylist/assets/9382674/0bc4248d-ba90-4420-a68a-73b6cb249b5b)

**Comment by Yuki2718** [comment]
I don't see cookie banner on bing except for mobile where `.bnp_cookie_banner` is irrelevant.

**Comment by THEtomaso** [comment]
> Okay, reproduced all the issues.

Great!
The issue with the missing login dialog @ `copilot.microsoft.com` still remains though.
It needs to be addressed in '**AdGuard Popups filter**', like I pointed out!

**Comment by Yuki2718** [comment]
Oh, I forgot to fix.

**Comment by THEtomaso** [comment]
Well done, Yuki2718!
Now I can go back to blocking Copilot again, with a good conscience! :)
