### ISSUE TITLE
coomer.su kemono.su

### ISSUE THREAD

**Issue by Daxy7** [easylist/easylist#18275]
tracker
```
||coomer.su/api/v1/andagain
||kemono.su/api/v1/andagain
```

**Comment by Daxy7** [comment]
@Yuki2718 tracker
```
||coomer.su/api/v1/welcomeback
||kemono.su/api/v1/welcomeback
```

**Comment by Linxgos** [comment]
Needs update using new url `kemono.su/api/v1/YourRetardAssBrokeActualSiteFunctionality-TryToFavoriteAnything-AllOfThisOverNginxLevelsOfLogs-GoodLuckWithTheSisyphianTask-NowChangeTheFuckingMethodToPatch-WeWillHaveOurFunThere` as the url name implies now uses patch method instead of post also apparently blocking all post xhr requests broke site functionality what got admin very upset. lul

**Comment by Yuki2718** [comment]
Maybe we can wait for reporter to give the url of blocked requests when the breakage occurs.

**Comment by 12cowdog72** [comment]
With all due respect, blocking all POST XHRs is absolutely idiotic. Are you trying to break sites and make this list worthless? Since you can't be bothered to verify yourself, the routes you broke are

* https://kemono.su/api/v1/favorites/post/:path/:path/:path
* https://kemono.su/api/v1/favorites/creator/:path/:path
* https://kemono.su/api/v1/:path/user/:path/post/:path/flag

Consider taking the advice the admin left you to heart.

**Comment by Daxy7** [comment]
@Yuki2718 P:
```
@@||://kemono.su^*/favorites/*$xhr,1p
@@||://kemono.su^*/user/*$xhr,1p
```

**Comment by Yuki2718** [comment]
@Daxy7 Too broad and allows circumvention. Can you list full URLs to write regex rules?

**Comment by Daxy7** [comment]
only favoriting with an account is broken as per directory name
```
https://coomer.su/onlyfans/user/heatheredeffect/post/867939443
```
```
https://coomer.su/api/v1/favorites/post/onlyfans/heatheredeffect/582512454
@@||://coomer.su/api/v1/favorites/post/$xmlhttprequest
@@||://kemono.su/api/v1/favorites/post/$xmlhttprequest
```
! unknown breakage
```
https://coomer.su/onlyfans/user/vixibun/post/531635210
https://kemono.su/api/v1/favorites/creator/
```

**Comment by ambigravity** [comment]
The current filters are too brittle, and fall short of enabling all the "proper" site functionality. I suspect that a whitelist method is simply not sufficient for this. POST is used for dynamic functionality, and blocking all of it by default is overaggressive.

Concrete example: favouriting posts is still broken by this filter, because the regex used is incorrect. Take note of @12cowdog72's message:

```
https://kemono.su/api/v1/favorites/post/:path/:path/:path
```

That's three trailing `:path` components, not two. The first is the service name, the second is the creator ID, and the third is the post ID.

Even then, the regex used is excessively brittle:

```
^https:\/\/kemono\.su\/api\/v1\/favorites\/(?:creator|post)\/(?:[a-z]{6,16}\/){1,2}\d{8,9}$
```

The service name is assumed to be between 6 and 16 characters, and the creator ID is assumed to be either 8 or 9 digits. The latter is definitely not correct; in theory the creator (and post) IDs can be any natural number with any number of digits, and it furthermore seems to vary based on the service in question.

Beyond this, I took a (non-exhaustive) look around, and there seem to be other normal site functions which make use of POST. At least one involves submitting a form. This filter breaks them.

I do get that the site operator has been renaming a route in order to stop it from being blocked by this list and has even gotten rather cute about it ("tryagain" -> "andagain" -> "welcomeback"), which I assume motivated the blanket POST ban, but unfortunately it is a reality about these kinds of things that a sufficiently motivated and attentive site operator can always work around a block list, since we're forced to be reactive to their design decisions. That's too bad, but breaking the site is probably not the ideal response, and affects both users and the maintainability of the list, since whitelisting individual endpoints is much more labour-intensive. It's also ultimately no more reliable, in the end, since the site operator can observe our whitelisting choices and design an API that sneaks through the inevitable gaps. The end result in that case is a more broken site which is, nevertheless, not fulfilling any of this list's goals.

I do get that playing whack-a-mole is not desirable and is even frustrating, but I think the blanket POST ban needs to be reconsidered.

**Comment by Daxy7** [comment]
Can't find `auth_id` to verify form.

![image](https://github.com/easylist/easylist/assets/91396482/1a77b029-d277-4b24-a083-3880b364e16c)

**Comment by Yuki2718** [comment]
@ambigravity That's not an example, please give actual URLs. Locking down is common practice here, I just didn't spent time to create proper exception as I was (and is) busy. The site owner can still circumvent or even break their own site (but then it's not our repsonsibility) in which case we will proceed to the next step.
