### ISSUE TITLE
SI.com slideshows getting blocked

### ISSUE THREAD

**Issue by mmortal03** [easylist/easylist#18285]
#### List the website(s) you're having issues with:

`https://www.si.com/nba/lakers/news/lakers-news-looking-at-trade-for-former-first-round-point-guard-rks97`

#### What happens?

Slideshow is completely blocked.

#### Screenshot(s) 

![Screenshot 2024-01-12 162148](https://github.com/easylist/easylist/assets/8298277/f9ccbb09-8f28-489d-a89d-0807cd603e12)

![Screenshot 2024-01-12 162553](https://github.com/easylist/easylist/assets/8298277/6b458c23-9443-4817-abcf-1f92f76c8b2f)

#### Filter lists you're using:

EasyList

#### Your settings:

- OS/version: Windows 10
- Browser/version: Chrome 118.0.5993.89
- Ad block extension/version: uBlock Origin 1.52.2

**Comment by THEtomaso** [comment]
It's because '**EasyList**' blocks the **EX.CO** player, which is known adware/spyware.
The remaining placeholder can be removed with `si.com##.is-exco-player`.

There is however a problem with the embedded YouTube vide too.
It fails to load with uBO, due to a redirect rule found in '**AdGuard Tracking Protection filter**':
https://github.com/AdguardTeam/AdguardFilters/issues/139827#issuecomment-1891049087

**Comment by THEtomaso** [comment]
> https://github.com/easylist/easylist/commit/0d601c8fc2f0b0eb549ca11d35538dc576ad03c5

Did you even test it?
For the slideshow to actually work, it requires far more whitelistings than that!

**Comment by Khrin** [comment]
@THEtomaso Thank you, https://github.com/easylist/easylist/commit/ae59c67ca857ee31fd8d0776d1aabdae9dc70667
