### ISSUE TITLE
Easylist + Fanboys social list causing high extension process cpu usage across a widespread amount of sites

### ISSUE THREAD

**Issue by Squall-Leonhart** [easylist/easylist#18300]
Not sure if this isn't Adblock plus itself (and i can't login to their site to bring it up), but myself [and others](https://www.reddit.com/r/chrome/comments/195g1s8/adblock_is_making_chrome_slow_to_a_crawl/) have noticed that Adblock plus is significantly delaying the load and page transitions of various domains, with the Extension itself hitting 100% process cpu time for the webextension process.

This is notable affecting

Mangadex
Youtube
Ubereats
Fansly
Onlyfans

in the case of Mangadex, ERR_QUIC_PROTOCOL_ERROR.QUIC_IETF_GQUIC_ERROR_MISSING is logged, but not without any filters

**Comment by Daxy7** [comment]
Uninstall ABP and install uBO.
https://github.com/gorhill/uBlock/

**Comment by Squall-Leonhart** [comment]
uBO is inferior to ABP and the developer has a misplaced superiority complex.

**Comment by Daxy7** [comment]
How so?

**Comment by m-fessler** [comment]
Seems to be a problem with ABP latest version, I have the same issues with Firefox.
I downgraded from version 3.22 (2024-01-09) to 3.17.1 (2023-06-16) - seems to work - hope for an update.

Greetings, Martin

**Comment by Squall-Leonhart** [comment]
Yes, this is a duplicate of https://github.com/easylist/easylist/issues/18271, dynamic content is destroying the filtering engine.

**Comment by Daxy7** [comment]
>dynamic content is destroying the filtering engine.
The 2005 code is destroying Adblock, actually

**Comment by Daxy7** [comment]
> Yes, this is a duplicate of #18271, dynamic content is destroying the filtering engine.

The AdBlock's 2005 code is destroying itself, actually.

**Comment by gorhill** [comment]
@Squall-Leonhart

> uBO is inferior to ABP and the developer has a misplaced superiority complex.

Since this comment attacking my character was apparently not worth hiding as "resolved" unlike the other to which it was responding, allow me to at least post objective information about the extensions which speaks for itself:

Link: `https://metalelf0.github.io/VimColorSchemeTest-Ruby/ruby.html`

<details><summary>Results:</summary>

![Screenshot from 2024-01-14 18-37-47](https://github.com/easylist/easylist/assets/585534/844c63a2-2c18-451e-8d33-d8b088735aaa)

![Screenshot from 2024-01-14 18-40-22](https://github.com/easylist/easylist/assets/585534/502d45fa-626e-4379-9808-f2c6e24c3794)

![Screenshot from 2024-01-14 19-27-09](https://github.com/easylist/easylist/assets/585534/47847513-0f54-43d1-9ac6-61904d265f2d)

</details>

**Comment by Squall-Leonhart** [comment]
didn't ask, cry harder
