### ISSUE TITLE
ad placeholders on wykop.pl

### ISSUE THREAD

**Issue by avanikaein** [easylist/easylist#18358]
#### List the website(s) you're having issues with:
`https://wykop.pl/`

#### What happens?
ad placeholder is visible 

#### Screenshot(s) 

![Screenshot 2024-01-22 at 3 05 43 PM](https://github.com/easylist/easylist/assets/56893063/5b243753-f094-47ba-99c4-7265494e7301)

#### Filter lists you're using:

ABP filters, Easylist
#### Your settings:

- OS/version: macOS Ventura 13.5.2
- Browser/version: Chrome Version 120.0.6099.129 (Official Build) (arm64)
- Ad block extension/version: Adblock Plus 3.22.1

#### Other details:

various ad placeholders on the website, all using selector `.pub-slot-wrapper`

**Comment by Daxy7** [comment]
blocked by regional Polish filters, disable ABP and install uBO in the extension app store:

![image](https://github.com/easylist/easylist/assets/91396482/dc51ad0a-b372-47cb-8fda-d8439ee1d076)

follow this guide to enable Polish filterlists:
https://github.com/gorhill/uBlock/wiki/Dashboard
if you are still stuck: (technical information)
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists

**Comment by dportvine** [comment]
You need add **EasyList Polish+EasyList**

<details>
<summary>Screen</summary>

![2024-01-23_095204](https://github.com/easylist/easylist/assets/111344219/f6441d22-0382-4a83-ab53-38cd1358771c)
</details>

**Comment by garry-ut99** [comment]
This is a regional website in polish language (PL), which requires additional regional filter list (PL in this case). 
Appropriate regional filter lists are enabled by default when installing AdBlock Plus in non-english language browsers, but since your browser language is english, hence no additional regional filter list has been enabled when you installed AdBlock Plus, and only EasyList has been enabled by default with your browser. While EasyList is a good starting point to block most of ads from all countires, it often requires additional supplemental regional EasyList filter list to be enabled to get full coverage of regional ads. 

You can activate the built-in `EasyList Polish` regional list in your AdBlock Plus's' advanced options, you should also additionally enable another good PL regional list: `Official Polish Filters for AdBlock, uBlock Origin & AdGuard` by visiting this link and clicking "Subskrybuj" button : `https://majkiit.github.io/polish-ads-filter/#oficjalne_polskie_filtry_do_adblocka%2c_ublocka_origin_i_adguarda`
