### ISSUE TITLE
vrtranspoint.fi: cookies/breakage

### ISSUE THREAD

**Issue by ntoskrnl11** [easylist/easylist#18461]
#### List the website(s) you're having issues with:

`https://www.vrtranspoint.fi/`

#### What happens?

Cookie notice is hidden, but page is not interactable/usable because the body still has the `modal-open` class.

To use the site, you basically have to disable your ad blocker (or the cookie notice list), reload the page, decline cookies, and re-enable your blocker.

#### Screenshot(s)

N/A

#### Filter lists you're using:

EasyList – Cookie Notices

#### Your settings:

N/A

#### Other details:

This is a common issue with generic cookie notice filters. I don't know how it could be properly fixed.

**Comment by Khrin** [comment]
There is no apparent break in this domain.

**Comment by Yuki2718** [comment]
@ntoskrnl11 Check if `/cookie-consent.min.js` is correctly blocked. ELC blocks this and tI can reproduce only if I unblock this.

**Comment by ntoskrnl11** [comment]
@Yuki2718 Thank you, `/cookie-consent.min.js` is not blocked for me because "Adblock List for Finland" has a rule that allows it. So this is an incompatibility issue between EasyList Cookie Notices and Adblock List for Finland. It should probably be fixed in the latter. CC @Nojuuu @peace2000

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c4b54baec543d7b7ffbb5f410f78f6f9d188bf1b

Videos are broken if that script is not whitelisted.

![kuva](https://github.com/easylist/easylist/assets/17256841/fd3ad663-fab2-4d93-8884-5b52fc2566f6)

"Videos can't be shown. Check cookie settings."

(That video in the link doesn't exist but as it still displays the nag, it means that whitelisting the script is still needed.

Added trusted-set-cookie filter to uAssets: https://github.com/uBlockOrigin/uAssets/commit/757b039441196cf1771dc5e37727440fa642649a

@Khrin or @Yuki2718 please accept this: https://github.com/easylist/easylist/pull/18627 so that the issue is fixed upstream.
