### ISSUE TITLE
k5a.io blocked on EasyPrivacy

### ISSUE THREAD

**Issue by tarjeigilbrant** [easylist/easylist#18974]
Our domain k5a.io, which powers Kilaya analytics for premium news publishers, is listed on EasyPrivacy. We emphasize our strong privacy measures: we don't store any personal data, only aggregating general stats like page views and time spent. 

Privacy is a major selling point for us, distinguishing us from other tools. We believe there's no infringement on privacy, and we kindly request to be removed from the list. For more details on our privacy approach, check out our privacy policy here: `https://www.kilkaya.com/privacy`

Best regards,
Tarjei Gilbrant
CEO, Kilkaya

#### List the website(s) you're having issues with:
Here is a list of some of our customers who are experiencing issues with the script being blocked:

```
www.zeit.de
www.sueddeutsche.de
www.20min.ch
www.schwaebische.de
www.nrk.no
www.dr.dk
www.svt.se
www.bt.dk
www.merkur.de
www.ilsole24ore.com
southwarknews.co.uk
```

#### What happens?

The script served from the domain k5a.io is blocked using e.g. Ghostery or any blocker using the EasyPrivacy list.

#### Screenshot(s) 

<img width="579" alt="image" src="https://github.com/easylist/easylist/assets/166812273/30ff3a44-9255-4c82-b69a-7da076aae1aa">

**Comment by Yuki2718** [comment]
We doesn't distinguish analytics. We are not an orginization and it's impossible for us to check and monitor allegation of privacy. The only question we have to ask is what the issue is for user, here the definition of user is those who visit these sites and not the site owner. I don't see any noticeble problem.

**Comment by THEtomaso** [comment]
@tarjeigilbrant:
You need to provide steps on how to reproduce the exact issues for each site.
Only then can potential exceptions be added by the filter list maintainers.

--

@Yuki2718:
In the OP's defence, I DID actually encounter an issue, due to `k5a.io` being blocked @ `tv2.no`, a couple of years ago:
https://github.com/lassekongo83/Frellwits-filter-lists/issues/98#issuecomment-1048079485

Amongst the other sites, mentioned by the OP, I also visit `nrk.no` regularly, but haven't noticed any such issues there.

**Comment by tarjeigilbrant** [comment]
Ok – I thought the idea was to block trackers who didn't care about privacy.

Blocking the domain will also affect the user for those customers who get content recommendations blocked. These recommendations are general recommendation based on aggregated data and not in conflict with any privacy.

One example can be seen here: 
`https://www.tv2.no/sport/fotball/premier-league/ten-hag-nektet-a-svare-forlot-pressekonferansen/16610566/`

With k5a.io allowed:
<img width="264" alt="image" src="https://github.com/lassekongo83/Frellwits-filter-lists/assets/166812273/84ccdd2b-258e-49a5-8a53-64e0745723d5">

With k5a.io blocked:
<img width="309" alt="image" src="https://github.com/lassekongo83/Frellwits-filter-lists/assets/166812273/ffc0646b-0064-434a-a924-242ac9a7adcd">
There are no recommendations below "Mer innhold fra TV 2" (more content from TV 2).

Again, these recommendations are not in conflict with any privacy.

**Comment by THEtomaso** [comment]
> There are no recommendations below "Mer innhold fra TV 2" (more content from TV 2).

To be honest, that appears to be highly preferable, rather than something that can be categorized as actual breakage.
@Yuki2718: I suggest cleaning up the leftovers with `tv2.no##.article-recommended`

**Comment by Khrin** [comment]
There is no need to remove the filter.

**Comment by Yuki2718** [comment]
> I suggest cleaning up the leftovers with tv2.no##.article-recommended

EP doesn't add specific cosmetic filters.

**Comment by THEtomaso** [comment]
I know, but '**AdGuard Other Annoyances filter**' and '**EasyList - Annoyances**' does.

**Comment by Yuki2718** [comment]
AG adds cosmetic filter by tracker, so no problem in adding to TPF. TBH I rather want EP to address these placeholder/leftover and suggested in internal chat.
