### ISSUE TITLE
pixiv.com infinite reload due to the EasyList – Cookie Notices

### ISSUE THREAD

**Issue by rainbowflesh** [easylist/easylist#19101]
pixiv.com infinite reload due to the `pixiv.net##+js(set-cookie, privacy_policy_agreement, 6, , reload, 1)` from `EasyList – Cookie Notices`.
Temporary solution is add `pixiv.net##+js(set-cookie, privacy_policy_agreement, 6, , reload, 1)` to filter.

**Comment by friendlyanon** [comment]
Introduced in https://github.com/easylist/easylist/commit/44fbecfbaee2824461d6f00c0104e12c1d199bbd by @ryanbr

**Comment by jackrjli** [comment]
The refresh loop occurs if you have both the EasyList and AdGuard cookie notices lists enabled. EasyList has `pixiv.net##+js(set-cookie, privacy_policy_agreement, 6, , reload, 1)` while AdGuard has `pixiv.net##+js(set-cookie-reload, privacy_policy_agreement, 5)`. If they're the same number there's no problem, but if they're different then you get this refresh loop. My guess is that Pixiv increments the number each time they update their privacy policy and that's why the numbers are different between the two lists.

As a workaround, I disabled the AdGuard rule by adding the following to my filters:
```
pixiv.net#@#+js(set-cookie-reload, privacy_policy_agreement, 5)
```

**Comment by ryanbr** [comment]
Disable ADG filter until its fixed
