### ISSUE TITLE
https://example.com/api/frontend-metrics

### ISSUE THREAD

**Issue by nothingisdead** [easylist/easylist#19380]
#### List the website(s) you're having issues with:

https://example.com/api/frontend-metrics (on any self-hosted [Grafana](https://github.com/grafana/grafana) instance)

#### What happens?

This URL is being matched by the following rule in [easyprivacy_general.txt](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt):

/frontend-metrics^

#### Filter lists you're using:

EasyPrivacy

#### Your settings:

I am using uBlock Origin with default settings.

- OS/version: macOS/14.4.1
- Browser/version: Firefox/127
- Ad block extension/version: uBlock Origin/1.58.0

#### Other details:

It looks like this pattern was added for a specific website (https://www.autoscout24.it/). Should it go in easyprivacy_specific.txt?

**Comment by drewmmiranda** [comment]
For what its worth i cannot find any info about what this URL is even for or supposed to do which is concerning. Blocking it appears to not harm grafana's functionality in any way. I cannot find any way to disable it either. Hopefully grafana can provide some insigh.

**Comment by Khrin** [comment]
> Should it go in easyprivacy_specific.txt?

No.

**Comment by nothingisdead** [comment]
What was the resolution here? Is there a reason to block this URL pattern across the board?

**Comment by joshhunt** [comment]
FWIW, as I shared back in https://github.com/grafana/grafana/issues/89437#issuecomment-2181050062, this endpoint does not 'phone home' back to Grafana - it only reports metrics to the operators of the Grafana server (you if you self host) and I don't believe it consitutes a leak of any more information than regular API calls necessary for using Grafana.

Blocking this has no impact to functionality, other than the annoying error toast (though that will be suppressed in future updates https://github.com/grafana/grafana/pull/89379). Personally, I would prefer if this rule was removed from the default list to solve the annoying notification, but otherwise I have no stake. 👍
