### ISSUE TITLE
https://www.helpscout.com/beacon-messaging/

### ISSUE THREAD

**Issue by Charca** [easylist/easylist#19577]
#### List the website(s) you're having issues with:

`https://www.helpscout.com/beacon-messaging/`

#### What happens?

There should be an icon on the bottom right of the page that lets customers email or chat with customer support agents.

#### Screenshot(s) 

![CleanShot 2024-07-17 at 11 44 00@2x](https://github.com/user-attachments/assets/b82dd6d0-1e51-4065-83ca-d1b479cfe260)

#### Filter lists you're using:

EasyList, EasyPrivacy

#### Your settings:

- OS/version: macOS 14.5
- Browser/version:  Chrome 126
- Ad block extension/version: AdBlock 6.5.0

#### Other details:

It appears that Help Scout's messaging/chat product Beacon was [recently added](https://github.com/easylist/easylist/commit/70ee9bc2416b356fcfecdb59fe123911d6fef1bd) to the EaslyList and EasyPrivacy third-party lists, which prevents users from using it to contact customer support agents. Despite its unfortunate name, Beacon is not a "beacon" from a tracking perspective, it's a messaging widget similar to the ones offered by Intercom or Zendesk. You can find more information about Beacon on this [docs site](https://docs.helpscout.com/article/1250-beacon-jumpstart-guide).

The affected URLs are:

- `||d3hb14vkzrxvla.cloudfront.net^` on the easylist_thirdparty list
- `||beacon-v2.helpscout.net^` on the easyprivacy_thirdparty list

**Comment by tedeling** [comment]
This is very unfortunate as the inclusion disables the contact-us widget in our app.  https://docs.helpscout.com/article/911-beacon-and-ad-blockers

**Comment by ryanbr** [comment]
Fix this tracking; `beacon-v2.helpscout.net` and we'll remove it.

`!function(n){var a=n.getElementsByTagName("script")[0];function e(e){var t=n.createElement("script");t.type="text/javascript",t.async=!1,t.src="https://beacon-v2.helpscout.net/"+e,a.parentNode.insertBefore(t,a)}var t=navigator.userAgent&&navigator.userAgent.toLowerCase(),r=t&&(-1<t.indexOf("trident")||-1<t.indexOf("edge/")),t=t&&-1<t.indexOf("bingpreview/1.0b");r||t||(e("static/js/vendor.5fe8f3bc.js"),e("static/js/main.ec7c4297.js"))}((window,document));`

**Comment by jakubjanczyk** [comment]
Hey @ryanbr!

I am developer at Help Scout and I'd like to clarify the purpose of this code. It's not intended to track anything, it's our "loader" file that we ask our customers to embed on their sites, and the content of this file will make sure to get the latest scripts from our server (`main.*.js` and `vendor.*.js`), to show end users Beacon, that they can use to contact support team of our customers. We add some script tags to fetch those files, but this is rather common thing many other widgets like this are doing.

We are very much against unwanted tracking and we don't do it here, nor we show any ads or anything similar. Yes, in this script we check for user browser, but it's only because our Beacon doesn't work on Internet Explorer or old Edge versions. So instead of causing errors on users end, we simply don't load it. Something that users could appreciate. We don't send this information anywhere.
In fact, some other messaging widgets, from other companies, check for even more things in their scripts. We try to keep it as light as is possible, just to ensure our Beacon works.

De-uglifying this code makes the logic a bit more clear:
```
!(function (n) {
    var a = n.getElementsByTagName("script")[0];
    function e(e) {
        var t = n.createElement("script");
        (t.type = "text/javascript"), (t.async = !1), (t.src = "https://beacon-v2.helpscout.net/" + e), a.parentNode.insertBefore(t, a);
    }
    var t = navigator.userAgent && navigator.userAgent.toLowerCase(),
        r = t && (-1 < t.indexOf("trident") || -1 < t.indexOf("edge/")),
        t = t && -1 < t.indexOf("bingpreview/1.0b");
    r || t || (e("static/js/vendor.5fe8f3bc.js"), e("static/js/main.ec7c4297.js"));
})((window, document));
```

I hope this will remove confusion and prove that we are not tracking anything here 🙂 However, if you still disagree, I'd very much appreciate pointing out which part is doing the tracking, and I'd be very happy to solve it to improve quality of our products for users.

Thank you!

**Comment by Charca** [comment]
Hi @ryanbr, I saw that you unlisted our Cloudfront URL on https://github.com/easylist/easylist/commit/199ba5323cdc5a529a1b705532c94cd015058352 — I appreciate it 🙏

Have you had a chance to review my teammate Jakub's comment above regarding the JS snippet? As he mentioned, the script is not doing any tracking, but if you think otherwise or have any concerns about it, please let us know and we'd be happy to work with you to address them.

Thank you in advance!

**Comment by AdventureBeard** [comment]
The inclusion of Helpscout on Easylist has been catastrophic for my customer support.

**Comment by Khrin** [comment]
Fixed in https://github.com/easylist/easylist/commit/9032ca8ce76522c3362e9853a583ce241c0fde10
