### ISSUE TITLE
https://www.lilly.com

### ISSUE THREAD

**Issue by ss-221** [easylist/easylist#20187]
#### List the website(s) you're having issues with:

https://www.lilly.com/

#### What happens?

Cookie banner is visible

#### Filter lists you're using:

uBOLite ([annoyances-cookies](https://ublockorigin.github.io/uAssets/filters/annoyances-cookies.txt) and [easylist-cookies](https://ublockorigin.github.io/uAssets/thirdparties/easylist-cookies.txt))

#### Your settings:

- OS/version: macOS Sequoia
- Browser/version: Google Chrome 130.0.6723.59
- Ad block extension/version: uBlock Origin Lite
2024.10.14.189

**Comment by CocoaTheCat** [comment]
Why are we doing this? Because the authors of this list disregard the rights of website owners to hide their content when ad-blockers are used. We don't support aggressive ads and use ad-blockers ourselves. Our only reason for this action is to oppose the unfair practice of blocking entire websites (showing a white screen) when ad-block list authors can't detect or hide ads selectively.
