### ISSUE TITLE
Easyprivacy blocks Paypal login through Ebay

### ISSUE THREAD

**Issue by peace2000** [easylist/easylist#3787]
### List the website(s) you're having issues:

`https://www.ebay.com/` and `https://www.paypal.com/`

### What happens?

I cannot login to Paypal through Ebay which is needed if you want to pay your shoppings by using Paypal.

### List Subscriptions you're using:

Easyprivacy

### Your settings

- OS/version: Win 10
- Browser/version: Firefox 68
- Adblock Extension/version: Ublock Origin 1.20.2

### Other details:

This rule fixed it for me:

`@@||www.paypal.com/webapps/helios/api/log?event=IC*$image,domain=pay.ebay.com`

Rule that caused this issue:

`/api/log?`

**Comment by ryanbr** [comment]
I've had no issues previously, I don't trust this request to be honest.

**Comment by JZebra** [comment]
I am also having similar issues, specifically with the `c.paypal.com^` rule.

I think the request is being blocked because the `braintree-web/data-collector` uses it: https://braintree.github.io/braintree-web/current/DataCollector.html

But this client is necessary for Paypal to function. It creates a device fingerprint that paypal *requires* in order to authenticate a transaction. 

I think this rule should be removed.
