### ISSUE TITLE
[incorrect blocking] smartsuppchat.com

### ISSUE THREAD

**Issue by tohoracek** [easylist/easylist#3868]
Hi, we are having troubles with the loading of our live chat **[Smartsupp.com](https://smartsupp.com)** widget on sites that using EasyPrivacy list (https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt)

Chat is loaded from **smartsuppchat.com** and this domain is blocked.

See details on this screen:

![smartsupp](https://user-images.githubusercontent.com/2698797/62218178-3d8e6600-b3ac-11e9-8046-108818172c4d.png)

### List the website(s) you're having issues:

- travelking.cz
- figures.cz
- smartsupp.com
- and many others

### List Subscriptions you're using:

EasyPrivacy list (https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt)

### Your settings

- OS/version: MacOS 10.14.5
- Browser/version: Chrome 75.0.3770.142
- Adblock Extension/version: uBlock v0.9.5.18

### Other details:

No of our major competitors like intercom.com, drift.com, tidio.com or crisp.chat are listed in the list.

**Comment by okiehsch** [comment]
> Adblock Extension/version: uBlock v0.9.5.18

This is fixed in `uBlock Origin` since [last september](https://github.com/uBlockOrigin/uAssets/commit/9f6b17b86705b189f39ec7379d6c31b487aeca8d)
I am not sure if you intend to use `uBlock` instead of `uBlock Origin`.
I am pretty sure that the vast majority of adblock users who have `EasyPrivacy` enabled are using
`uBlock Origin`.

**Comment by Khrin** [comment]
yeah @okiensch now you can remove that filter
