### ISSUE TITLE
EasyPrivacy - remove @@| |ninja.onap.io/ninja-cee.js$domain=olx.pl

### ISSUE THREAD

**Issue by maciejtarmas** [easylist/easylist#477]
Please remove the exception `@@||ninja.onap.io/ninja-cee.js$domain=olx.pl` from easyprivacy_whitelist_international.txt

This script is not essential for proper functioning of olx.pl and the domain is flagged as potential malware all over the internet.

This was committed here by @monzta : 
[https://github.com/easylist/easylist/commit/cfb8d88e90c8e45d55e80a6fd88b54f18f8f627c](url)

**Comment by SMed79** [comment]
> the domain is flagged as potential malware all over the internet.

Why? Proof?

**Comment by maciejtarmas** [comment]
Safari flags it as dangerous,  for example.

There's a JavaScript file that gets downloaded from this domain, targeting Internet Explorer and trying to modify the registry. At least that's what I read, cause I'm no JavaScript guy, so the code means nothing to me.

Anyway, the file from that domain is downloaded by the mobile version of olx.pl at olx.pl/i2/ but it is not required for the site to function properly.

I run a public Polish list filtering ecommerce sites for over 4 years so I guess I kinda know what I'm doing. I blacklisted the domain, but EasyPrivacy overrides my filter.

I would still like to know why that domain is whitelisted.

I can't check the exact file that gets downloaded right now. I'll post a link tomorrow.

**Comment by maciejtarmas** [comment]
OK, I've done some more research on this thing.

Safari no longer flags the site as malware.

Still, the script seems to be at least trying to get the user's Windows computer name.

The script is only downloaded on the mobile version of the site at olx.pl/i2/ right now. That's just a waste of resources, since it's not going to work on mobile, only on desktop.

Again, why the heck was this exception added?

Please, remove it.

**Comment by Ravizz** [comment]
@maciejtarmas: 
> Again, why the heck was this exception added?
> Please, remove it.

Probably/maybe to fix broken sorting buttons, because if removed, the sorting buttons get broken, an example of STR on FF 57.0.4 & uBlock Origin v1.14.25rc1:

1) remove the exception (or alternatively `/ninja.js$important,domain=www.olx.pl` can be used as an override)
2) go to example category (computers): https://www.olx.pl/elektronika/komputery/
3) at top-right click at one of the three sorting buttons: Najnowsze / Najtańsze / Najdroższe  (which means The most recent / The cheapest / The most expensive)
4) notice that the sorting button will work a single/first time only
5) notice that the sorting buttons are now broken and do not work anymore
6) with the exception enabled again + steps 2-3 repeated, notice that the buttons work again/always

So the exception rule should not be removed.
