### ISSUE TITLE
https://www.techjunkie.com/how-to-get-movies-plex/

### ISSUE THREAD

**Issue by AnonymousPoster** [easylist/easylist#4781]
### List the website(s) you're having issues:

`https://www.techjunkie.com/how-to-get-movies-plex/`

### What happens?

Banners, popups

### List Subscriptions you're using:

EasyList, Adblock, own

### Your settings

- OS/version: Linux 5.0.0-38-generic
- Browser/version: FF
- Adblock Extension/version: uBlock

### Other details:

Rules created by the "Picker"

```
! 1/23/2020 https://www.techjunkie.com
www.techjunkie.com##.modal--download.modal
www.techjunkie.com##.is_stuck.fixed-sidebar-fire-tv
www.techjunkie.com##.fixed-sidebar-fire-tv
```

**Comment by THEtomaso** [comment]
> ```
> ! 1/23/2020 https://www.techjunkie.com
> www.techjunkie.com##.modal--download.modal
> www.techjunkie.com##.is_stuck.fixed-sidebar-fire-tv
> www.techjunkie.com##.fixed-sidebar-fire-tv
> ```

That will result in a disappearing scrollbar.
Try this instead:
```
techjunkie.com##.fixed-sidebar-fire-tv
||techjunkie.com/wp-content/themes/techjunkie/js/bioep.min.js
```

**Comment by spirillen** [comment]
I can confirm @THEtomaso suggestion is working

**Comment by THEtomaso** [comment]
Additionally, the Social Media icon in the site's page header is blocked.
This blocking is wrong, because the button doesn't actually link to any social media sevices, but rather to a section of social media related articles.

**Problem filters:**
* Fanboy's Annoyance List
* Fanboy's Social Blocking List

**Problem rule:**
`##.icon-social`

**Possible fix:**
`techjunkie.com#@#.icon-social`

(@Khrin)

**Comment by THEtomaso** [comment]
@Khrin:
ryanbr seems to have acted to fast.
The newsletter subscription prompt (##.modal__box) still pops up after a while (10-60 sec.).
To properly prevent it, without any unwanted side-effects, simply block the script which I pointed out to here:
https://github.com/easylist/easylist/issues/4781#issuecomment-578175623
