### ISSUE TITLE
OT and yet... about `mediaset.it`

### ISSUE THREAD

**Issue by spirillen** [easylist/easylist#4887]
If you can speak Italian or even know a lot more about [mediaset.it](https://www.mypdns.org/ticket/190) I would appreciate any sharing of knowledge for how much it would be possible to block to enhance your privacy in my [DNS Firewall](https://www.mypdns.org/wiki/DnsFirewall)

**Comment by Khrin** [comment]
Mediaset owns the biggest commercial television network in Italy, `mediaset.it` is their main domain (for example `https://www.mediasetplay.mediaset.it/` is used for their video on demand service, `https://www.tgcom24.mediaset.it/` is one of the most visited news website in Italy, etc) and `mediaset.net` is used for their CDN, as far as I know.

About the subdomains you're referring, I don't know for what are used for, looking at the name the second address is used to deliver their HbbTV services (`https://www.hbbtv.org/`), so in all likelihood aren't used for tracking/delivering advertisements.

I'm closing here, because isn't related to EasyList subscriptions.

**Comment by spirillen** [comment]
Hi @Khrin That's also more than I did know :smile: Thanks.

Was also only asking here as the the user-base is a hole lot bigger and hoping for more solid input.
