### ISSUE TITLE
ftuapps.dev

### ISSUE THREAD

**Issue by reypryma** [easylist/easylist#5074]
### List the website(s) you're having issues:
ftuapps
onehack.us

### What happens?

nano defender fail to bypass
### List Subscriptions you're using:

nano adblocker
### Your settings

- OS/version:  Windows 10
- Browser/version: Firefox 74.0
- Adblock Extension/version: 
latest in this 17 maret 2020
### Other details:
If you stop reload the web, the block doesnt show, it seem the block only load after web load done

**Comment by llacb47** [comment]
`onehack.us` fixed if you update `ublock filters`.

for `ftuapps.dev` add `ftuapps.dev##+js(nostif, offsetHeight, 200)`

@mapx-

**Comment by 411621** [comment]
![FTU apps ad blocker message](https://user-images.githubusercontent.com/29167457/203130729-0c59828e-cdb2-4e36-abe8-55349edf86bf.jpg)

**Comment by 411621** [comment]
Since over a week (11/09/22none my browser including freshly installed browsers cannot access ftuapps.dev.
I ran several virtual machines, with newly installed browsers, same problem.
the window gets darkened out in the red framed alert message pops up:

**Blocked because of at blocker
it seems that you are using some at blocker software which is preventing the page from fully loading.  Please white list this website or disable ad blocking software**

but I have not ad blocker installed!
Even if I disable my [ESET] antivirus completely [insane] the same error message occurs.
To me quite evidently it is is a site configuration problem.

**Comment by mapx-** [comment]
MAybe your browser has a builtin blocker (brave, opera, edge, vivaldi etc have such blockers) or the tracking protection in your browser is ON (strict modality could block some requests the website is checking to see if an adblocker is running)

**Comment by 411621** [comment]
Hello mapx and thank you for your reply.
the problem suddenly popped up, as mentioned in early November.
by now I have tried it in virtual machines, with other clean installed browsers, but all to no avail.
In my opinion is definitely a site problem.

**Comment by 411621** [comment]
PPS Same as OP: "If you stop load/reload of the web page, the block doesn't show, it seems the block starts only load after site page load is done"

**Comment by mapx-** [comment]
Did you check your browser for builtin blockers / protection thing ?

I disabled uBO adblocker, tested the site without it and still no issue.

**Comment by mapx-** [comment]
brave browser => shields ON, no adblocker => getting the "issue"
firefox, strict ETP => getting the "issue"

**Comment by 411621** [comment]
same here again since May 2024
I'm being blocked as well. Created a Windows 10 virtual machine total clean install with no antivirus or ad blockers installed. 
Same problem. I also had upgraded to Firefox 127 when I thereafter noticed this issue.
One site recommended to uninstall Firefox 127... DUH!?

**Comment by ShadowSpawnFromBeyondTheStarsGF** [comment]
@411621 @mapx- @reypryma please STOP visiting FTUApps as they were caught distributing malware: https://www.reddit.com/r/Piracy/comments/120xk62/psa_ftuapps_removed_from_megathread_for/
https://www.reddit.com/r/haitenjp_is_scam_site/comments/1g5ho5i/ftuapps_included_malware_in_their_topaz_video_ai/

Also, check your computer with another antivirus for any malware that FTUApps may have infected you with.
I propose that we add every FTUApps domain (ftuapps.dev, ftuapps.io, etc.) to the block list.
