### ISSUE TITLE
Please consider removing stat-track.com as a Fingerprinter.

### ISSUE THREAD

**Issue by gentgaashi** [easylist/easylist#5102]
Hi all,

It has come to our attention that stat-track.com was classified as a Fingerprinter because it was referencing a redundant library that we were using.

The script was used to create a unique user id so that no other personal information was stored and captured. However, that beacon and the data it produces was never used. In fact, we have disabled that beacon and it should no longer get deployed on any traffic. Overall, that domain is part of Moosend.com and implements various types of subscription forms for websites (https://moosend.com/subscription-forms/).

Could you re-consider your classification please?

Thanks

**Comment by ryanbr** [comment]
Was classified as a tracker, has this changed?

**Comment by yannnis** [comment]
Hi all,

Yannis here - CEO at Moosend. This is what's loading subscription forms. It was classified as a fingerprinter in another service and this has changed. One of our developers used a library - fingerprint2 I believe - and we have completely removed the library and code since it wasn't even used anywhere. The domain name is massively unfortunate but it was something we already had available. I have also started a conversation on reddit https://www.reddit.com/r/uBlockOrigin/comments/fextvk/ublock_blocking_moosend_web_form/

Let me know if this makes sense?

**Comment by ryanbr** [comment]
Note; `stat-track.com` is also blocked in the `disconnect list` which also weighs on this.

A quick review of `https://cdn.stat-track.com/statics/moosend-tracking.min.js`

```
Tracking Page view
Tracking Actions.
Tracking Exits.
Cookies setting/getting.
Mouse Tracking
LocalStorage / UUID tracking
```
Easyprivacy is specifically designed for blocking tracking scripts. and this script has too much privacy issues. Due to privacy, it's fine to keep this domain blocked.

**Comment by yannnis** [comment]
Thanks for coming back to me

It's fine to keep any tracking aspects blocked if you like . For example
any calls made to t.stat-track.com are tracking calls. Having said that
there are other calls on that script that are now blocked since you are
blocking the whole domain including the cdn domain (cdn.stat-track.com).
The other calls in that script render subscription forms so I don't see why
they should be blocked as well.

In addition, even the tracking calls (t.stat-track.com) are heavily
anonymized. Shouldn't that be enough to allow them too?

About disconnect, we are in similar discussions . We just noticed this
issue and started taking actions.

Let me know if you have any questions?

**Comment by yannnis** [comment]
Hi @Khrin - Can I please ask why this was closed? What do you need to remove stat-track.com as a fingerprinter?
