### ISSUE TITLE
connect.nosto.com

### ISSUE THREAD

**Issue by trackerless** [easylist/easylist#5174]
### List the website(s) you're having issues:
```
https://www.flightclub.com/
https://www.grasscity.com/
https://www.kotsovolos.gr/
https://www.cyberpuerta.mx/
https://www.bonnegueule.fr/
https://www.apoteket.se/
https://www.maxbo.no/
```

### What happens?
Nosto Tracker is not blocked.

### List Subscriptions you're using:
EasyPrivacy

### Your settings
uBlock

- OS/version: Ubuntu 18.04
- Browser/version: Chrome, Latest
- Adblock Extension/version: uBlock 1.24.4

### Other details:
Following rule should resolve issue
||connect.nosto.com

**Comment by Khrin** [comment]
I don't think it's a tracker. (It's already blocked in the Fanboy's Annoyances List)

**Comment by spirillen** [comment]
Hi @Khrin 

I tent to disagree
> across product recommendations, content, triggered overlays and popups, category pages, and more. 

> implemented new personalization campaigns site-wide

But whether it is a tracker..... I would expect some tracking in relation to the above text, otherwise there product is fake marketing

![image](https://user-images.githubusercontent.com/44526987/79249933-495c8280-7e7e-11ea-948b-85c63cfffaf3.png)

![image](https://user-images.githubusercontent.com/44526987/79250162-94769580-7e7e-11ea-8a32-b7523a624b4e.png)
