### ISSUE TITLE
Hope remove googleadssl.l.google.com

### ISSUE THREAD

**Issue by iamsurfing** [easylist/easylist#5204]
This rule make me can not use Google inputtools.

ssl.gstatic.com.        2400    IN      CNAME   gstaticadssl.l.google.com.
gstaticadssl.l.google.com. 2400 IN      A       203.208.41.63
gstaticadssl.l.google.com. 2400 IN      A       203.208.41.47
gstaticadssl.l.google.com. 2400 IN      A       203.208.41.55
gstaticadssl.l.google.com. 2400 IN      A       203.208.41.56

**Comment by ryanbr** [comment]
@mapx-

**Comment by mapx-** [comment]
@iamsurfing provide the steps to reproduce the issue

**Comment by iamsurfing** [comment]
It is hard, because sometimes ssl.gstatic.com has CNAME , gstaticadssl.l.google.com , and sometimes not. It is depend on Google DNS.

I am sorry.

I have added it to my whitelist.

**Comment by DandelionSprout** [comment]
@iamsurfing If this is still a problem after 16 months (It's only last night that I started a drive to go through 2020 EasyList reports), the uAssets team has requested to be told at https://github.com/uBlockOrigin/uAssets/pull/9624 where/how the input tools are being blocked, in order to write a working CNAME-specific whitelist entry.

**Comment by iamsurfing** [comment]
Thanks for your help. However, what about fonts.gstatic.com?
Google fonts static is used in lot of websites.


fonts.gstatic.com.      3564    IN      CNAME   gstaticadssl.l.google.com.
gstaticadssl.l.google.com. 3564 IN      A       203.208.40.66
gstaticadssl.l.google.com. 3564 IN      A       203.208.40.66

**Comment by ryanbr** [comment]
No longer applicable.
