### ISSUE TITLE
Kommune.no - Error reporting service(s) blocked (EasyList)

### ISSUE THREAD

**Issue by THEtomaso** [easylist/easylist#5220]
### Affected domain:
`kommune.no` (not directly accessible)

### Example:
`https://www.molde.kommune.no/meld-feil/`
(other subdomains might be affected too, because there are many of them)

### Issue:
At the above example page, the error reporting service is blocked (unable to load).

### Screenshot:
![filterissue-moldekommune](https://user-images.githubusercontent.com/9382674/79047508-4d3a9b80-7c17-11ea-83a3-28e76816baf7.jpg)

(Translation: "**Laster Nabolaget**" = "**Loading Neighbourhood**")

### Problem filter:
* EasyList

### Problem rule:
`/nb_front.js`

### Blocked asset (at the subdomain example):
`https://www.molde.kommune.no/kunde/grensesnitt/i18n/nb_front.json`

### Elaboration:
"**nb**" in nb_front.json probably stands for Norwegian Bokmål, which is the most common written standard in Norway.
Therefore, this type of asset naming scheme might also be used by other Norwegian sites.
Another potential problem rule, in this regard, is this one: `/nb/frontend.js`

### Possible fix (avoiding potential issues with both JSON and Norwegian sites):
```
- /nb_front.js
- /nb/frontend.js

+ /nb_front.js$script,domain=~no
+ /nb/frontend.js$script,domain=~no
```

### Temporary fix (for the known issue only):
`@@/nb_front.js$domain=kommune.no`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.9.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout

**Comment by kulfoon** [comment]
> THEtomaso:
>
> Deleting the problem rule entirely might be a better solution, as "nb" in nb_front.json probably stands for Norwegian Bokmål, which is the most common written standard in Norway.
> Therefore, this type of asset naming scheme might also be used by other sites.
> Another potential problem rule, in this regard, is this one: `/nb/frontend.js`

Disagree, instead of removing, just adding`$script` option to the affected filter `/nb_front.js` is enought, then it will no longer block `.json` legitimate `xhttmlrequest` s (which is the case in your issue) while still blocking `.js` `script` request. And why we do still need to block `.js` `script` requests is because they are required to block exads on pornsites:
https://github.com/sanosay/exads-adblock
https://github.com/uBlockOrigin/uAssets/issues/6151#issuecomment-524312826
https://github.com/easylist/easylist/blob/3b40f8882633e858b06aad18a0f55c32136c3488/easylist/easylist_general_block.txt#L8111-L8161

**Comment by THEtomaso** [comment]
> instead of removing, just adding `$script` option to the affected filter `/nb_front.js` is enough

I agree.
_First post edited_

**Comment by DandelionSprout** [comment]
Would something like `@@/nb_front.js$domain=~no` (To whitelist the `.no` TLD) be a good idea, or would it seem weird?

**Comment by THEtomaso** [comment]
Actually, that doesn't work.
It would have to be `@@/nb_front.js$domain=~.no`

**Comment by DandelionSprout** [comment]
Okay, so I managed to accidentally do a double whitelisting in my example above. It's been a long day for me, it seems. I should of course have written `/nb_front.js$domain=~no`.

**Comment by THEtomaso** [comment]
Of course.
But I'm still baffled as to why `@@/nb_front.js$domain=~.no` works as a whitelisting.

**Comment by DandelionSprout** [comment]
I learned about using TLD as `$domain=` less than 7 hours ago, so any kind of experimentation and resulting documentation would've been awesome to have.

**Comment by THEtomaso** [comment]
Anyway, these are all of the potential problem rules (which includes /nb)
```
/nb-back-sol?
/nb/avanti.
/nb/b_lo.php
/nb/frontale.
/nb/frontend.js
/nb_front.js
```
What do you think..
Should `$domain=~no` be added to all of them?

**Comment by THEtomaso** [comment]
@DandelionSprout:
How about adding that "Temporary fix" (which I provided in the first post) to your Nordic list?
There's no telling how long my report will linger here.

**Comment by kulfoon** [comment]
> THEtomaso : https://github.com/easylist/easylist/issues/5220#issuecomment-612979640 :
> 
> Of course.
> But I'm still baffled as to why `@@/nb_front.js$domain=~.no` works as a whitelisting too.

Coz when using `.` uBO expects lower level domain in front of it, must be: `~kommune.no` or `~*.no`
If `~.kommune.no` then must be `~molde.kommune.no` or `~*.kommune.no`
If `~.molde.kommune.no` then must be `~www.molde.kommune.no` or `~*.molde.kommune.no`
but you can just skip a leading `.` at all, fo ex. `~no` or `~kommune.no` or `~molde.kommune.no` or `~www.molde.kommune.no`

> THetomaso : https://github.com/easylist/easylist/issues/5220#issuecomment-612982032 :
> Anyway, these are all of the potential problem rules (which includes /nb)
>
> ```
> /nb-back-sol?
> /nb/avanti.
> /nb/b_lo.php
> /nb/frontale.
> /nb/frontend.js
> /nb_front.js
> ```
>
> What do you think..
> Should `$domain=~no` be added to all of them?
> Personally, I think the latter two looks most troublesome.

I think that before adding anything to any of these, you should provide at least one real case of a broken website for each of these filters, to prove they (the filters) need to be fixed/changed, there is too much potential speculation whether any websites are broken by any of these filters.

Also adding `$domain=~no` as a solution instead of `$script` doesn't seem a good idea, because such filter will allow exads on `.no` pornsites, for ex on `somepornsite.no.`

**Comment by THEtomaso** [comment]
I think you would have a much harder time finding a `.no` porn site, which uses scripts like that for ads, rather than a site which uses `/nb_front.js `or `/nb/frontend.js` for benign purposes.

**Comment by kulfoon** [comment]
I haven't searched yet, it was a warning, but have tried right now and indeed couldn't find any as well, so I must agree, but nor you provided any real cases of websites broken by any of these filters, except `/nb_front.js` of course, and even as for `/nb_front.js` you provided a real case of `/nb_front.json` blocked **file** only and not of a `/nb_front.js` **script** file, thus adding `script` is enought to fix the case, and there is no reason to replace it with wider fix like `$domain=~no` to cover potential/specluated `.js` script cases. I'm just for fixing actual real cases rather than fixing all potential / speculated cases and replicating fix to other unaffected filters, it's just too preventive.
