### ISSUE TITLE
cian.ru

### ISSUE THREAD

**Issue by vladostman** [easylist/easylist#5715]
### List the website(s) you're having issues:

https://krasnoyarsk.cian.ru/

### What happens?

There is a menu at the top of the page, the last element in that menu is an ad. They seem to be custom crafted/native ads.

![img](https://user-images.githubusercontent.com/66869331/87271625-fab29900-c4fd-11ea-8531-890a4237050a.png)

### List Subscriptions you're using:

AdNauseam default: AdNauseam lists, EasyList, uBlock lists.

### Your settings

- OS/version: Windows 7
- Browser/version: 78
- Adblock Extension/version: AdNauseam 3.9.109

### Other details:

`cian.ru##li#special-promo-link-container` should do it for all cities (first part of the domain)

**Comment by DandelionSprout** [comment]
Appears to me to have been fixed in RU AdList through `cian.ru###special-promo-link-container`.

**Comment by vladostman** [comment]
oh so I'm not supposed to be submitting what's in there already? 

My logic was that many people never learn about the existence of additional lists (I learned about them only yesterday) and therefore never enjoy the benefits of disabling native ads.

**Comment by DandelionSprout** [comment]
For uBO users who've set their browser language to Russian, Ukrainian, Belarusian, Kazakh or Uzbek at the time of installing uBO, *RU AdList* is enabled by default, to the best of my knowledge. It's also considered to be affiliated with EasyList, since it has [its own subboard on the Lanik forum](https://forums.lanik.us/viewforum.php?f=102).

So unless I'm completely wrong on this, those who visit Russian websites consistently are supposed to have RU AdList enabled.

**Comment by ryanbr** [comment]
Easylist = English only requests, closing
