### ISSUE TITLE
https://api.fpjs.io

### ISSUE THREAD

**Issue by Valve** [easylist/easylist#5775]
Note: If you're a website owner that has been specifically targeted, fix the site before reporting. 
Remove revolving ad servers, popup ads, adblock countering etc. Only then will this request be reviewed.

Hi, 

I see that our API endpoint got into your easyprivacy_trackingservers list.

Why was it included there?

Our API does not perform cross-site tracking or any tracking.
Happy to provide more information if needed.

**Comment by llacb47** [comment]
It is fingerprinting. So it should be included in EasyPrivacy.

**Comment by Valve** [comment]
Based on which policy or guideline @llacb47 ?

**Comment by ryanbr** [comment]
Was added here: https://github.com/easylist/easylist/commit/5fff056ec33

Easyprivacy stops tracking (1st and 3rd-party), which includes fingerprinting a user. Looking specifically at the script `https://cdn.fpjs.io/@2/fp.js`

1. User Agent checks
2. Use of cookies and local storage.
3. Language, screen, fonts, date/timezone, system checks.
4. Also checking/tracking Adblock elements.

Regardless on how its used, it's still tracking the end user which is why it's in Easyprivacy.

**Comment by Valve** [comment]
Thanks
