### ISSUE TITLE
EasyPrivacy - sdk.privacy-center.org

### ISSUE THREAD

**Issue by jawadst** [easylist/easylist#6049]
I work at Didomi, a consent management platform using the domain sdk.privacy-center.org.
For the last couple of weeks, we have been getting reports from various websites using our consent notices that users do not see consent notices and are not able to give or deny consent anymore when they are using the EasyPrivacy list.

After doing some research, I found the following commits that are impacting the categorization of the domain:
 - https://github.com/easylist/easylist/commit/4f0c8be28d6b3492fad4d5c1c423d06b384e356e#diff-15ee6a169e8a825881d5a18bbd703425
 - https://github.com/easylist/easylist/commit/b6bd67b6108701dcdf22ae025ddeee95626d0d3f

Can I ask what the logic is behind changing the categorization for the domain?

### List the website(s) you're having issues:

Any website using Didomi, like https://www.gamestar.de/

### What happens?

The consent notice is not displayed to the user who cannot give or deny consent as per the regulation.
This blocking affects various features of websites that need consent information to know what they can do and what features can be enabled on a website. On some websites, video players do not run, for instance.

### List Subscriptions you're using:

EasyPrivacy

**Comment by THEtomaso** [comment]
> Can I ask what the logic is behind changing the categorization for the domain?

**EasyPrivacy** doesn't contain whitelistings for `sdk.privacy-center.org` anymore, because it doesn't contain any blocking rules for it either.

The filter that you refer to is called **EasyList Cookie List**.
It blocks third-party connections to `privacy-center.org` by default, but also contains whitelistings for the following sites:
```
ivoox.com
lavanguardia.com
mundodeportivo.com
```
--

> On some websites, video players do not run, for instance.

I'd advice you to post examples which demonstrates that breakage, because these things are never whitelisted solely on good faith.

--

Other blocking filters:

**AdGuard Annoyances filter** blocks third-party connections to `privacy-center.org`, but contains whitelistings for the following sites:
```
elmundo.es
gamestar.de
mundodeportivo.com
nieuwsblad.be
rtl.fr
softonic.com
standaard.be
telegraaf.nl
```

**I don't care about cookies** blocks connections to `sdk.privacy-center.org`, but contains exceptions for the following sites:
```
dumpert.nl
funradio.fr
mundodeportivo.com
rtl.fr
telegraaf.nl
```

Hope this helps.

**Comment by momala454** [comment]
@jawadst as you work for didomi, please provide an easy way to block the popup without blocking the videos

**Comment by THEtomaso** [comment]
https://github.com/easylist/easylist/issues/17456/
