### ISSUE TITLE
thegay.porn [NSFW]

### ISSUE THREAD

**Issue by Yuki2718** [easylist/easylist#6052]
### List the website(s) you're having issues:

`https://thegay.porn/en/`

### What happens?

1. Missed ads/placeholder

<details>

![thegay](https://user-images.githubusercontent.com/58900598/92919534-a4b19180-f46b-11ea-8b41-b7fa3f38ef3a.png)

</details>

2. Popunder on clicking any video

### List Subscriptions you're using:

uBO default + AGJPN

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 80.0.1
- Adblock Extension/version: uBO 1.29.2

### Other details:

In the SS ads are blocked by `||a1p5pst3ore.online^` in uBlock filters. Hiding the placeholder completely requires `:abp-has`. For the popunder `||thegay.porn/poppy/$script`.

**Comment by spirillen** [comment]
This issue have been tranfered to a tracking free environment at [My Privacy DNS](https://www.mypdns.org/)

The other beneficial of this is, the issue have been hidden and therefor not distributing any adult contents unless you have been signing up for the [adult projects](https://www.mypdns.org/project/view/10/) and signed the Legal Form [L5](https://www.mypdns.org/L5)

The new location for this issue is: <https://www.mypdns.org/search/query/Qrk4t_ULZMbq/#R>
