### ISSUE TITLE
Welt.de Zeit.de Spiegel.de cookie permissions

### ISSUE THREAD

**Issue by Speciesx** [easylist/easylist#6076]
### List the website(s) you're having issues:

Zeit.de
Welt.de
Spiegel.de

### What happens?

Is it possible to bypass the cookie permissions?

![zeit](https://user-images.githubusercontent.com/1196375/93625942-ffef0100-f9e2-11ea-97fb-c9a0515b0743.PNG)
![spiegel](https://user-images.githubusercontent.com/1196375/93625943-00879780-f9e3-11ea-99d4-ee6635f45a40.PNG)
![welt](https://user-images.githubusercontent.com/1196375/93625947-01b8c480-f9e3-11ea-91c1-b06f6b95ab5d.PNG)

### List Subscriptions you're using:

![92415176-0adea180-f158-11ea-921b-cd4b3b1b21d4](https://user-images.githubusercontent.com/1196375/93625812-d8983400-f9e2-11ea-8548-dabeb8115c2e.png)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox nightly
- Adblock Extension/version: uBlock Origin 1.29.2 + Cookie AutoDelete

**Comment by THEtomaso** [comment]
This has recently been discussed (look under closed issues).
The same cookie consent exists on many German sites.
Blocking it will break video playback (and possibly other things too).

**Comment by Speciesx** [comment]
I don't care about the video playback.
Can you post the blockings rules?

**Comment by THEtomaso** [comment]
> Can you post the blockings rules?

You can use this rule to block the popup @ `welt.de`:
`||privacy-mgmt.com^$domain=welt.de,important`
It will break video playback, and possibly some other things too.

Blocking the ones at spiegel.de and zeit.de will basically break everything!

**Comment by terr72** [comment]
Consider me an illiterate when it comes to the capabilites of advanced filter rules,hence the possibly dumb question:
would it be possible to trigger an accept via a filter rule with some JS magic for those sites?

**Comment by krystian3w** [comment]
Only in AdGuard.

Addons like: `uBO` / `ABP` & `AdBlock` no have scirptlets/snippets to accept these pop-ups.

`Nano Adblocker `may only accept in `Nano Base` / `Nano Annoyance` on real cookie walls:
- `zeit.de`
- `spiegel.de`

The `welt.de` have options to reject these permissions and possible read only texts and images - so may no worth Nano AdBlocker policy about cookie walls (the policy gives users the choice of whether to accept or modify the required number of approvals to a minimum).

**Comment by terr72** [comment]
Is there already such an AdGuard scriplet rule?

Given that AdGuards scriplets are intended to be cross-compatible with [uBO's scriptlet extension](https://github.com/uBlock-user/uBO-Scriptlets), I've just added it to `userResourcesLocation` in the advanced settings, applied the changes and reloaded all AdGuard filters lists, but the problem at welt.de persists.

The cookie consent popup is really designed to be as change-unfriendly as possible, so I guess most people click on accept without a change to save time anyway. I wouldn't mind if this is done by default by AdGuard annoyances instead of going into the hassle of creating rejection rules for every possible choice.

**Comment by krystian3w** [comment]
As they AdGuardTeam will add (no exist yet), it is probably write filter incompatible with uBO  & Nano / ABP & AdBlock:

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules-1
