### ISSUE TITLE
https://crypto-loot.com/

### ISSUE THREAD

**Issue by Zhangsun321** [easylist/easylist#655]
new coin miner url
https://i.imgur.com/YAz8Rhm.png
thanks..

**Comment by SMed79** [comment]
https://github.com/easylist/easylist/commit/3ef91c1515ea2490da5d5022a85ef473a25394fc#diff-dbc51871bdd5cf7971a65ef9684d2248

**Comment by Pocketart** [comment]
People are voluntarily allowing websites that use these miner scripts to mine on their computer in exchange for in-game tokens, bonuses, and to unlock content. And now since you blocked it, you will be depriving those sites of their revenue, even though their goal was to provide a sustainable ad-free experience for the user.

What happened to adblock in general?
At first we blocked ads because they were annoying and covered content, especially popups.
And then we had acceptable-ads that did not cover content and had vastly cleaner content, which adblockers still blocked anyway
And now we have an ad-free solution that still lets the website earn money. And congrats, you just blocked it.

More and more websites are turning to subscription-based access to content now because of adblock. And now i'm paying approx $400 a year on news, magazines, and columns that used to be free access.

This isn't what adblock was supposed to do; adblock was supposed to make our lives easier by blocking annoying popups and ads that affected us negatively. Instead its making our lives harder by forcing us (regular readers) to pay for the total money lost from adblockers.

Now that we have a new solution that can provide an ad-free experience for users while allowing the website to earn money, how about embrace it instead of ignorantly throwing it onto the list?

In the end, when you hurt a website, you are indirectly hurting their users because the website will eventually have to resort to a plan B or face bankruptcy.
