### ISSUE TITLE
theprovince.com, nationalpost.com, financialpost.com, etc

### ISSUE THREAD

**Issue by tisdall** [easylist/easylist#6651]
The issue reported in #6103 is back after commit 7de10e706353f80102e7010fe00e417b5ac3dcc0 .  I put blockquotes on the text I copy-n-pasted from the past issue that still applies.

### List the website(s) you're having issues:
theprovince.com
nationalpost.com
financialpost.com
torontosun.com
... all of the Postmedia sites

### What happens?
> All Postmedia sites fail to load the fem.js file which is responsible for incorporating multiple third-party functionalities. This includes things already blocked such as ad calls and analytics, but also calls to single sign-on and commenting on stories.

### List Subscriptions you're using:

Line in Easylist causing the block:  https://github.com/easylist/easylist/blob/7de10e706353f80102e7010fe00e417b5ac3dcc0/easylist/easylist_thirdparty.txt#L1775

### Your settings

I'm not using an adblocker

### Other details:

> I work for Postmedia.  I believe `fem.js` is safe to unblock as any functionality that a blocker would want to block is already blocked by blocking the third-party JS (ie Google Ad Manager, Google Analytics, MParticle, Google Tag Manager, etc.).  With `fem.js` blocked, the comments and sign in are broken.

**Comment by THEtomaso** [comment]
> `||d395dw5zk780j2.cloudfront.net^*/fem.js`

Even if that script is withelisted, the login function will still be broken by a bunch of other privacy filters/rules, which effectivelly blocks `rpxnow.com` and `tinypass.com`.
The best solution would be if webmasters cleaned up their own mess!

**Comment by tisdall** [comment]
@THEtomaso - The login functions were working fine prior to this addition to Easylist.

**Comment by THEtomaso** [comment]
> This includes things already blocked such as ad calls and analytics, but also calls to single sign-on and commenting on stories.

Such things should be separated!

--

> The login functions were working fine prior to this addition to Easylist.

Just amongst the filters that I'm using myself, these are the breaking ones:

* **Browse websites without logging in**
`||tinypass.com^$third-party`
(Broken login should be considered expected behaviour though, when using this filter)

* **EasyList**
`||d395dw5zk780j2.cloudfront.net^*/fem.js`

* **Fanboy's Enhanced Tracking List**
`||tinypass.com^$third-party`

* **hpHosts - Ad and Tracking servers only**
`widgets-cdn.rpxnow.com`

--

Possible fix:
```
@@||tinypass.com^$third-party,domain=financialpost.com|nationalpost.com|theprovince.com|torontosun.com
@@||d395dw5zk780j2.cloudfront.net^*/fem.js$third-party,domain=financialpost.com|nationalpost.com|theprovince.com|torontosun.com
@@||widgets-cdn.rpxnow.com^$third-party,domain=financialpost.com|nationalpost.com|theprovince.com|torontosun.com
```

**Comment by THEtomaso** [comment]
Also needed, because of `$generichide` entries in **uBlock filters** (@okiehsch):

Ads:
`financialpost.com,nationalpost.com,theprovince.com,torontosun.com##.ad__container`

Annoyances:
`financialpost.com,nationalpost.com,theprovince.com,torontosun.com##.newsletter-widget`

Social media:
`financialpost.com,nationalpost.com,theprovince.com,torontosun.com##.share-button__wrapper`
`financialpost.com,nationalpost.com,theprovince.com,torontosun.com##.social-follow`
`financialpost.com,nationalpost.com,theprovince.com,torontosun.com##.widget--social-share`

**Comment by ryanbr** [comment]
@tisdall  I've removed it. But from privacy point of view `https://d395dw5zk780j2.cloudfront.net/v23.1/fem.js` needs to change. Mixing ad, tracking, login calls,paywall into one javascript is **not welcome.**

**Comment by tisdall** [comment]
I'm not sure I understand the issue.  The one JS is essentially glue calling in all the different components.  All the unwanted components such as ads, analytics, etc are already blocked by ad blockers due to using well known third party providers.
