### ISSUE TITLE
ingest.sentry.io

### ISSUE THREAD

**Issue by hyperknot** [easylist/easylist#6963]
### List the website(s) you're having issues:

[Sentry.io](https://sentry.io/organizations/populus-wz/issues/) is a SaaS error tracker, used by multiple websites to report broken JavaScript behaviour. 

### What happens?

easyprivacy: `||ingest.sentry.io^` is blocking Sentry from being used.

### List Subscriptions you're using:

easyprivacy

### Your settings

uBlock Origin, but doesn't matter, it's in the blocklist.

### Other details:

Sentry has been broken and fixed here:
https://github.com/getsentry/sentry-javascript/issues/2916
https://github.com/uBlockOrigin/uAssets/commit/6489ab5eaf2a838bcdf2ae74ec8542ebb897d16d
https://github.com/uBlockOrigin/uAssets/pull/7924

**Comment by hyperknot** [comment]
Commit: https://github.com/easylist/easylist/commit/d1d108645fcd7e7742617a6fb483df41209b15cc

**Comment by jan-auer** [comment]
See also https://github.com/easylist/easylist/pull/6789#issuecomment-753894515

**Comment by ryanbr** [comment]
Happy to keep it. We block event, error trackers.

**Comment by piotr-cz** [comment]
@ryanbr 
please refer to previous discussion we've had few months ago: https://github.com/uBlockOrigin/uAssets/pull/7924

**Comment by myusuf3** [comment]
Please undo this. This isn't something I would enjoy seeing blocked as an engineer.  This discussion above linked by @piotr-cz is useful to read.

**Comment by Zopieux** [comment]
Bystander here. I'd like to point out that while there might be good reasons to block *all* third party assets, as block list maintainers we're basically in the business of deciding what trafic is harmful to the user and what isn't, on behalf of the user, who trusts EL with carefully tuned filter lists.

I don't work for Sentry nor use their products. As opposed to the cesspool of privacy-invading ad/spy/malware companies Easylist blocks, Sentry [engaged with the adblock communities](https://github.com/uBlockOrigin/uAssets/pull/7924) and took the time to explain what they do and why, investigating/debunking specific technical claims and answering questions. They demonstrated a level of transparency and honesty that is nowhere to be seen in the ad world Easylist is supposed to be fighting – precisly because they are not in the ad business but rather offering developer tooling. Contrary to most companies out there, they adopted a business model based on a [fully open source core](https://github.com/getsentry/sentry), that anyone can inspect, which further shows they come with good intentions and aren't hypocrites.

I believe this request is therefore quite reasonable and deserves a bit more attention.

**Comment by brpaz** [comment]
Tools like Sentry are essential for any engineering team to proactively detect errors in their applications. Errors that can deeply affect the User experience. 

Blocking this will be bad for everyone. Engineering teams will be in the dark and users can have a frustrating experience while using unstable applications.

Please reconsider.

**Comment by mitsuhiko** [comment]
@ryanbr is there a way to have a conversation about this? This keeps coming up from developers and customers. What would have to change about the system so you're okay with unblocking it?

**Comment by armenzg** [comment]
I'm baffled about this decision. As an engineer, I'm trying to provide great value to our customers by knowing when my product is buggy. We are reporting errors to Sentry so we can build better software. 

We're not trying to track the users across sites or harvest their data, thus, I can't understand why there would be a reason to block it!

**Comment by spirillen** [comment]
It's disturbing to see how many :+1: tracking gets while the project purpose is anti tracking, and that gets all those :-1: 

You should really have a look in the mirror and ask your self if you liked a jackass in your pocket tracking all your movements, writing them down only to sell it to people like Trump and Cambridge ana(l)lytics

If this was in the US and somebody was following you this tight into your bedroom/bathroom etc you would have shot them. but because it is done by bits you believe it is different?? 

Everyone but @ryanbr deserves 100 :-1:

**Comment by dcramer** [comment]
@spirillen I would suggest taking the time to understand what is and isn't tracking. Sentry is _not_, factually, tracking. It is used to capture code diagnostics. We do not set cookies, we do not sell data, and we don't provide any kind of user 'tracking' functionality whatsoever.

Please keep the discussion civil.

**Comment by piotr-cz** [comment]
@spirillen
Please take 5 minutes to read what tools like Sentry or Firebase Crashlytics are about.
I think yours and @ryanbr's opinion about them is based on misunderstanding their puprose.

When you use some application which shows errors or crashes, I don't think you use to take time to create crashdump, write down reproduction details and send it to developers.

At least my experience is that users do it rarely - and when they do, they are very imprecise like: _App doesn't work_, _App is broken_; but still expect me to fix the problem somehow.

Error reporting/ crash reporting tools help us here.

**Comment by umaar** [comment]
Not associated with sentry or this tool and haven't followed all these convos and linked issues much, but I understand Sentry is currently blocked in this list, and I guess ublock origin? Tbh I can see both perspectives, the dev in me knows how useful the extra diagnostic information is (in fact it's what I'm using to try and fix some bugs my users are experiencing!), but on the other side, I see the _default_ setup of Sentry captures these on a JS error:

- My IP address
- My browser version
- My operating system + version

Which some users may not want to be collected, regardless of the reasons behind the collection. Is it possible for Sentry to work with the devs to find a middle-ground? E.g. maybe a "minimal" endpoint which only collects a stacktrace - and is not blocked, but then another endpoint which includes everything as it is now. Not saying that's a good idea just sharing a thought.

**Comment by dcramer** [comment]
@umaar IP you can't prevent (its client side ultimately), and the browser/OS are actually very important. Think about internet explorer era when so many bugs were specific to IE. Its less of a common thing these days, but it is still important debug information to understand aggregate trends. The real use case these days: "is the new version of our code causing more issues in Firefox?"

**Comment by umaar** [comment]
Preaching to the choir :) As mentioned I'm using Sentry myself to investigate some bugs. It's more about finding a middle ground which works with Sentry, but also with blockers. Maybe no middle ground can be reached, and that's ok too.

**Comment by pgl** [comment]
Heya. Just thought I'd chime in with a couple of comments.

First I think this is to do with policy, rather than Sentry specifically. Is the policy to block all data about user behaviour being sent to third parties?

The situation is that _any_ data about users' browsing behaviour being sent to a third party is usually abused, either right away or at some point in the future. It's common for companies to claim that it's not being abused, but there's so many counterexamples to trust these claims by default.

So a policy to block any data being sent to third parties is on balance probably better than not.

I like Sentry and I think it's a great service. But if a user decides (via proxy, if they're using EP) to block data being sent to the Sentry servers, then I think that should be respected.

**Comment by mlazowik** [comment]
The thing is thet unless someone explicitly tries to do so you can't track users via Sentry, there's not enough data.

Maybe another option is to go from `EasyList/EasyPrivacy` to `EasyList/EasyPrivacy/EasyNuke` and let users decide if they want to block non-privacy infringing developer tools?

**Comment by ThiefMaster** [comment]
Yeah I was about to suggest the same: Wouldn't it make sense to split EP into those *clearly* bad/commercial trackers (Zuck & co) and a separate list that is much more strict and also includes stuff like sentry and similar error logging tools.

**Comment by ryanbr** [comment]
It's tracking/logging/monitoring events done through directly or indirectly by the user when the load a site. Which is why it's blocked. Which is specifically covered in https://github.com/easylist/easylist/blob/master/README.md#easyprivacy

- Impressions/Event/Perf/Pageview logging

I don't want my browsing behavior (which is essentially what it is) in any form to leave my machine, or communicated with another script or server.

**Comment by mlazowik** [comment]
OK, that makes sense, but arguably the `EasyPrivacy` name is not conveying this behaviour to users. This is where the suggestion to split is coming from.

**Comment by mitsuhiko** [comment]
> I like Sentry and I think it's a great service. But if a user decides (via proxy, if they're using EP) to block data being sent to the Sentry servers, then I think that should be respected.

I mean I use easylist myself but I would like to be able to draw a difference between something that actually tracks me and something that is a crash reporter or else. After all particularly me using ad blockers often breaks websites so I want developers of those websites to be able to fix up their website so it works with trackers blocked.

**Comment by pgl** [comment]
> I would like to be able to draw a difference

Add the relevant domains to your allow list? *You* know the difference, in this case, but the average user doesn't and you probably wouldn't be able to make the same judgement call on every other entry in the list.

**Comment by armenzg** [comment]
Is there a way to do the following?

* A user visits a website that users service X for error reporting
* The user is prompted, this site uses error reporting with service X; do you consent error reports being submitted?
  * If they say 'yes' then eventual errors will be allowed
  * If they say 'no' that's the end of it

**Comment by ThiefMaster** [comment]
Unless only triggered when an error is supposed to be reported OR once per service (e.g. once for sentry) that would be incredibly annoying.

**Comment by mlazowik** [comment]
> And there are a lot of examples of companies going bad - they get acquired or the developers get tired, and then data is being sold to whoever offers the most.

@pgl to make it clear – data gathered via Sentry is not enough to track users, someone would have to explicitly abuse Sentry for that. Normally it's less complete than regular HTTP access logs.

**Comment by jonilgz** [comment]
This is just a non-sense decision.

**Comment by bogdan-calapod** [comment]
We are developing a private B2B app and heavily use Sentry especially while testing to ensure that our users do not encounter bugs / help fix them quickly.

We display a very light error message to the user, and expect details to come through Sentry. This decision is nonsense - it breaks a lot of stuff, causes more issues than it is worth and doesn't really help anyone.

I get the privacy argument, but water's also good for you. Too much though and you will drown.

**Comment by jonilgz** [comment]
I mean... if anyone want´s to track users, there is a lot of better ways to do without Sentry. You dont need to pay a 3company or buy an instance of Sentry, you can do it for free.

Again this is a non-sense decision and what you get with that, its to sites block users that use adblocks, so your idea of a better internet are going down. Adblockers start being more agresive that ads, and that is very very wrong.

**Comment by RhavoX** [comment]
Do you guys know that sentry can use a server side pass-through feature (aka tunneling) when a log is sent to server side API which relays to sentry directly? It is not hard to setup and works flawlessly providing as much info as a normal client side solution.
So first of all blocking error logging is just plain stupid and second of all this block can be defeated entirely, all it requires is some more work for developers. Work that shouldn't be necessary.

In such a case you still think this should be in this list? Why make lives harder if the end result is the same?

**Comment by nikola-team-ai** [comment]
> Do you guys know that sentry can use a server side pass-through feature (aka tunneling) when a log is sent to server side API which relays to sentry directly? It is not hard to setup and works flawlessly providing as much info as a normal client side solution. So first of all blocking error logging is just plain stupid and second of all this block can be defeated entirely, all it requires is some more work for developers. Work that shouldn't be necessary.
> 
> In such a case you still think this should be in this list? Why make lives harder if the end result is the same?

And what if we use client side react (CRA)? We cannot rely on this...

**Comment by Khrin** [comment]
I believe that this insightful discussion ended long ago.
