### ISSUE TITLE
zdnet.com

### ISSUE THREAD

**Issue by kuro68k** [easylist/easylist#7021]
## List the website(s) you're having issues:

https://www.zenet.com

### What happens?

Cookie permission banner displayed.

### List Subscriptions you're using:

EasyList
EasyPrivacy
EasyList Cookie

AdGuard Tracking Protection
AdGuard Annoyances

Fanboy’s Annoyance

uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

### Your settings

- OS/version: Windows 10
- Browser/version: Chrome 87.0.4280.141
- Adblock Extension/version: uBlock Origin v1.31.2

**Comment by THEtomaso** [comment]
Needs to be allowed, in order to avoid breakage:
https://github.com/AdguardTeam/AdguardFilters/issues/58146/
https://github.com/easylist/easylist/issues/1676/
https://github.com/lassekongo83/Frellwits-filter-lists/issues/77/
https://github.com/ryanbr/fanboy-adblock/issues/1375/

Before filing such issues, you should check for whitelisting rules.
They usually exist for a reason!
