### ISSUE TITLE
healthline.com article section contents blocked

### ISSUE THREAD

**Issue by erincerys** [easylist/easylist#7179]
### List the website(s) you're having issues:

`https://www.healthline.com/nutrition/best-probiotic-supplement`

### What happens?

Contents of articles other than section headers (i.e. paragraphs of sections) are blocked

### List Subscriptions you're using:

EasyPrivacy found to be the cause.

### Your settings

- OS/version: ArchLinux
- Browser/version: Firefox 85.0
- Adblock Extension/version: uBlock 1.33.0

### Other details:

EasyList v202102071134 contains the following filter rule that matches the parent `div` containing essential content:

```
healthline.com##.css-0 > div[class]
```

**Screenshot of page + inspector without modification:**
![2021-02-07-131725_1076x1232_scrot](https://user-images.githubusercontent.com/4268966/107160267-2558b900-694a-11eb-91a0-61306219e0c3.png)

**Screenshot of page + inspector with modification** such that the filter expression in question no longer matches:
![2021-02-07-132534_1048x1131_scrot](https://user-images.githubusercontent.com/4268966/107160279-3275a800-694a-11eb-84d5-94ab9942c850.png)

I fixed this manually in My filters with the following expressions:

```
healthline.com#@#.css-0 > div[class]
healthline.com##div[class="css-0"]:has(> div[class]:not(:has(> p)))
```

**Comment by llacb47** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
I can confirm the presence of this problem, and I propose that `healthline.com#@#.css-0 > div[class]` be replaced with `healthline.com##div.css-0 > div[class]:not([id])`

[The report where the faulty entry was added](https://github.com/easylist/easylist/issues/7050), was based on an example page that turned out to have a pretty different UI than the one in this thread.
