### ISSUE TITLE
https://reddit.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#7189]
### List the website(s) you're having issues:
https://reddit.com

### What happens?
There isn't enough cosmetic filtering in my opinion.

### List Subscriptions you're using:

uBlock Origin's default filter lists + Fanboy's Annoyance + uBlock -- Annoyances + Romanian Ad (ROad) Block List Light

### Your settings

- OS/version:  Microsoft Windows 10 Pro Version 10.0.19042 Build 19042
- Browser/version: Firefox Version 85.0.2
- Adblock Extension/version: uBlock Origin Version 1.33.2

### Other details:

**www.reddit.com##div._2vEf-C2keJaBMY9qk_BxVn:nth-of-type(2)** worked for me. (It's a filter.)

**Comment by yokoffing** [comment]
Please post a screenshot of what you think needs a cosmetic filter.

I will also add here there I wish Fanboy's Annoyance included cosmetic filtering of reddit's "Live Now" or "Popular Now" (I forget what they call it specifically) where there's a random unrelated live stream playing when you're scrolling through your post. I always have to block it manually. The latest filter that's worked for me in order to block this is `www.reddit.com##.scrollerItem.hrQ5rXDbyl6t3TIXxENXB._3Qkp11fjcAw9I9wtLo8frE._1EG7_Cm18ANvUvJ4rJdRgQ`

**Comment by ryanbr** [comment]
Closing, not enough info. Ancient request.
