### ISSUE TITLE
classicreload.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylist#7214]
### List the website(s) you're having issues:

`https://classicreload.com/joust.html`

### What happens?

Large placeholders above and beside the game frame.

### List Subscriptions you're using:

![image](https://user-images.githubusercontent.com/22780683/107856457-986d9e00-6e28-11eb-809d-ec53867b374e.png)

### Your settings

- OS/version: Windows 10 20H2
- Browser/version: Chrome 88.0.4324.150 x64
- Adblock Extension/version: uBO 1.33.3b0 + IDCAC 3.2.7

### Other details:

I propose:
```
classicreload.com##div[class^=region-sidebar-]
classicreload.com###content-top
classicreload.com###div-gpt-ad
```

The placeholders on the left and right are most noticeable if the window is between 1100px and 1600px wide.

![image](https://user-images.githubusercontent.com/22780683/107856558-35c8d200-6e29-11eb-9a62-8a19f41c349d.png)

**Comment by THEtomaso** [comment]
@DandelionSprout:
You missed this one: `classicreload.com###div-gpt-ad`
Please, add it to your post.

**Comment by DandelionSprout** [comment]
That one was only on the far bottom, but sure thing.

**Comment by THEtomaso** [comment]
I don't see it at the far bottom anywhere.
On the page that you posted as an example, it's pretty much located in the middle of the screen (right below the rating box).
Though it might require a `-abp-` fix, since it's inside of `###node-middle-block`, but somehow it works without it. :)
You'll find it on the front page too.
