### ISSUE TITLE
chinese smart tv tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#7746]
chinese smart tv - 创维电视(skyworth tv) tracker

```
gz-data.com (100% sure)
gzdata.com.cn (not sure)
gozendata.com

https://github.com/privacy-protection-tools/anti-AD/issues/402
https://github.com/privacy-protection-tools/anti-AD/issues/403
gzads.com
```

 Please refer to the article "My TV is monitoring all connected devices":
 https://www.v2ex.com/t/772523

 And these?
 https://gitee.com/bigdataleaveme/dontcollectme/raw/master/dontcollectme.txt

**Comment by ryanbr** [comment]
I don't see Easyprivacy being used on a TV, unless I'm missing something. @c2xusnpq6

**Comment by c2xusnpq6** [comment]
pls google: adguard home, nextdns😅😅😃🤝

**Comment by c2xusnpq6** [comment]
> pls google: `adguard dns`, `adguard home` (router), `nextdns`😅😅😃🤝

@ryanbr 

![image](https://user-images.githubusercontent.com/75058881/116845533-a86f6f80-ac18-11eb-8c8b-68566d47369f.png)

**Comment by c2xusnpq6** [comment]
ping?

**Comment by c2xusnpq6** [comment]
@Khrin

**Comment by spirillen** [comment]
> https://github.com/privacy-protection-tools/anti-AD/issues/402

Hi @c2xusnpq6 ice collection, but as mentioned elsewhere more about where what is found, and best of all some logs showing what which entry does of bad stuff.

If you can find that and post it to lists of https://mypdns.org/my-privacy-dns/matrix

Another thing you should think of in this issue is, non or only a select few actually have access to any of these network / devices to do any testing our self to verify what is going on. This deems it necessary for you to provide us with the needed documentation to be able to trust the commit. Just adding a bunch of domains with a few links to some very foreign language... well it is somewhat up hill for us to follow what is going on.

As you also can see in this little example, there are not much to back up your statements, no matter how right you are.

```shell
$:/var/storage/repos/github/Import-External-Sources/hosts-sources$ git grep 'gz-data.com'
$:/var/storage/repos/github/Import-External-Sources/hosts-sources$ git grep 'gzdata.com'
$:/var/storage/repos/github/Import-External-Sources/hosts-sources$ git grep 'gzads.com'
```

**Comment by ryanbr** [comment]
Check the 3 domains, nothing.

![gzads](https://user-images.githubusercontent.com/1659004/133008121-504adff9-5659-46ff-9d77-1f3c2a612fc2.png)

**Comment by spirillen** [comment]
> Check the 3 domains, nothing but just links
> 

Guessing you have a login to `https://publicwww.com/` :smiley: 

![image](https://user-images.githubusercontent.com/44526987/133045155-c8f8aa7d-f3ee-4b1d-954a-94629f57b7dc.png)
