### ISSUE TITLE
uBlock blocking any request from client side

### ISSUE THREAD

**Issue by TrofimenkoAI** [easylist/easylist#782]
Hi guys, I am here to find solution how to avoid uBlock on my website. Right now I am implementing online store with different fetch API functionality. My customers found that if uBlock active, all requests(POST, GET) not working :( I saw a lot of opened issues but the matter of short time to fix this thing, I'd like to ask how to deactivated this things for all customers who is using this plugin? Mb I should add some kind of script or ...? Sorry if this questions already exists, but I couldn't find any examples.

**Comment by Khrin** [comment]
What's your website?

**Comment by TrofimenkoAI** [comment]
@Khrin sorry it's NDA project, so I can't tell main source, but it's based on Symfony, so simple fetch/request blocked by uBlock, searching solutions how to avoid this problem, because on my application doesn't exist any kind of ad.

**Comment by Khrin** [comment]
At least is possible to have some kind of log transcript? Otherwise I'm not sure on how I can help you...

**Comment by TriMoon** [comment]
@TrofimenkoAI, you can't modify plugin state's using a javascript on a website.
If that would have been possible the whole internet's security would have been compromised, because malicious websites would have been able to do much more...

I suggest you to ask help at https://github.com/gorhill/uBlock
