### ISSUE TITLE
arc.io untracking ads

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#7872]
https://arc.io/ ---> `{your_website}/arc-sw.js`
```
/arc-sw.js
```
![image](https://user-images.githubusercontent.com/75058881/118351118-9680bb80-b58c-11eb-9780-da43be4c76af.png)

it's untracking ads, or.... just let it go? ha~

it just like coin miner, but lite version?

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/118351416-8538ae80-b58e-11eb-8115-a3536597fada.png)

**Comment by c2xusnpq6** [comment]
one more... https://joinmassive.com/ lite coin miner

**Comment by ryanbr** [comment]
Sample urls please @c2xusnpq6

**Comment by c2xusnpq6** [comment]
> Sample urls please @c2xusnpq6 

I don’t have a website, I can’t use that function, or you can apply for an account to find out

**Comment by spirillen** [comment]
Hey @ryanbr 

For what I can read from the site "offering" this snippet, I would probably actually classify it as malware as it is "hijacking" the users bandwidth and browser cache without there knowledge and this can clearly become a costly affair on metered connection, like the one I'm on right now.

This said, I wouldn't be affraid trying to add @c2xusnpq6 suggestion for a filter on this on a global level as suggested. 

Better on the safe side than sorry, if it turns out that there somehow should appear a naming match later, we should take it up at that time.

```
/arc-sw.js
```

> Arc uses only a small portion of spare bandwidth, imperceptible CPU, 300MB of browser cache, and only runs when a device is connected to Wi-Fi or Ethernet. Cellular bandwidth is never used. 

> Arc creates a communal, distributed CDN with the latest HTML5 APIs — WebRTC to connect browsers, Service Worker to fulfill requests, IndexedDB to cache data, and WebCrypto to do it all securely.

**Comment by c2xusnpq6** [comment]
similar mining platform:

> one more... https://joinmassive.com/ lite coin miner

**Comment by gruns** [comment]
Hi guys. :wave:

I'm Ansgar. I work on Arc.

I want to clarify a few things.

> I would probably actually classify it as malware as it is "hijacking"
> the users bandwidth and browser cache without there knowledge and this
> can clearly become a costly affair on metered connection, like the one
> I'm on right now.

- Arc never uses cellular bandwidth. If a device is on a cellular
  connection, Arc does not activate and no bandwidth is used.

  From https://arc.io:

  ```
  Arc uses only a small portion of spare bandwidth, imperceptible CPU,
  300MB of browser cache, and only runs when a device is connected to
  Wi-Fi or Ethernet. Cellular bandwidth is never used.
  ```

- We mandate that Arc's widget always be displayed in the lower left
  corner of all pages with Arc so users can learn about Arc and, if they
  so desire, opt out in a consistent manner from site to site.

    * https://arc.io/faq/#can-i-move-modify-or-hide-arcs-widget

  This is a universal, unwavering requirement.

- With adblock, as detected with DOM bait or if `tracker.arc.io` is
  blocked, Arc does not activate and instead:

    1. Requests and requires explicit user opt in.

  and

    2. No content is shared, or bandwidth used, until the user opts in.

  And a user's opt in isn't permanent, of course. After opting in, one
  can always later opt out through the same widget, too (which is always
  visible and interactible).

See prior uBlock discussion here:

  * https://github.com/uBlockOrigin/uAssets/pull/8874

And a demo of Arc with adblock here:

  * https://arc.io/adblockDemo/

I also created a PR three days ago to appropriately block
`sentry.arc.io` instead of the blanket `arc.io`. See https://github.com/easylist/easylist/pull/8011.

Thank you!

**Comment by spirillen** [comment]
> With adblock, as detected with DOM bait or if tracker.arc.io is
> blocked, Arc does not activate and instead:

>    Requests and requires explicit user opt in.

This is a very short note as I have the one foot out of the door..

Your malware didn't ask for any permission last night when i visited you site.

PS: thanks for the `tracker.arc.io` :+1:

PPS: I have a hole lot more to say about hacking into peoples browsers and stealing there bandwitdh :middle_finger:

**Comment by ryanbr** [comment]
I've yet to see "sentry.arc.io" to be used

**Comment by gruns** [comment]
> PPS: I have a hole lot more to say about hacking into peoples browsers
> and stealing there bandwitdh middle_finger

- No browsers are hacked.

  Website owners voluntarily install Arc to speed up their sites and
  support themselves in a manner that preserves the user experience (eg
  no banner ads) and respects user privacy and data (Arc doesn't track,
  collect, nor sell any). I.e., without ads.

- We purposefully built Arc so users can opt out with two taps/clicks:

    1) http://i.imgur.com/NHosyH6.png

    2) http://i.imgur.com/71ct2hU.png

  There is no technical requirement to do this. We built Arc this way
  because it's the right thing to do. We're users of the web, and
  adblock, too.

- When a user navigates away from a page with Arc, all activity
  ceases. Nothing runs in the background.

- Sites must display Arc's widget, unmodified, in the lower left corner
  so users can learn about Arc and, if they so desire, easily opt out.

  Sites that hide or modify Arc's widget are disabled, rejected, and
  blocked.

- Users are happy with Arc. 100 million people run Arc every month and
  Arc has a 0.4% (not a typo) opt out rate globally.

> Your malware didn't ask for any permission last night when i visited
> you site.

I can't reproduce this.

Below is a video I recorded and the steps I took therein. The video was
recorded on 2021/06/07 with Chrome v87.0.4280.88 + uBlock v1.35.2 with
EasyPrivacy paused so Arc (`arc.io/widget.min.js`) loads.

  * https://streamable.com/w7w9aa

Steps taken (eg to reproduce):

  1) Load https://arc.io (or any page with Arc). I loaded the page in
     Incognito to show behavior from a clean slate.

  2) Open Arc.

  3) Arc requests and requires explicit user opt in.

  4) User can alternate opt in and opt out, as intended.

I also built a demo page for adblock developers where you can always see
this behavior:

  * https://arc.io/adblockDemo/

> I've yet to see "sentry.arc.io" to be used

I consider that a good thing. :slightly_smiling_face: We try to fix bugs.

sentry.arc.io is only used to report errors -- both known errors, eg

```js
Vue.config.errorHandler = function (err, vm, info) {
    console.log('Vue global error handler', err, vm, info)
    Sentry.captureException(err)
    // https://vuejs.org/v2/api/#errorHandler
}
```

and uncaught errors that bubble up

  * https://sentry.io/answers/capture-errors/#uncaught-exceptions

During error-free execution, no exceptions are thrown and thus no
requests are made to sentry.arc.io.

You can see Sentry's client and sentry.arc.io being loaded in the
minified widget here:

  * http://i.imgur.com/3j1tZji.png

Alternatively, if Sentry's CDN, browser.sentry-cdn.com, is blocked for
you, then Sentry's reporting client in Arc will fail to load and no
requests to sentry.arc.io will be made.

**Comment by c2xusnpq6** [comment]
Have you ever imagined what would happen if a user was used to opening multiple tabs?...

Will the user's computer crash?....

Users in disadvantaged countries may have poor performance of their electronic equipment. How do you deal with this situation?..

**Comment by gruns** [comment]
> Have you ever imagined what would happen if a user was used to opening
> multiple tabs?...

Of course. 🙂

This is accounted for gracefully. All tabs with Arc communicate and
cooperate.

There is no difference in usage between 1 open tab with Arc and 10 open
tabs with Arc.

> Will the user's computer crash?....

Nope.

Fundamentally, if Arc harmed, or impacted, the user experience -- at all
-- websites wouldn't add Arc. See https://arc.io/faq/#does-arc-impact-the-user-experience

The opposite actually happens: websites with Arc load faster for users
because Arc securely retrieves content from other nearby devices instead
of distant datacenters.

> Users in disadvantaged countries may have poor performance of their
> electronic equipment. How do you deal with this situation?..

Arc requests and requires explicit user opt in with adblock, like
installed by users in such countries. Or any country.

Cellular data is never used.

And, of course, if any user is ever uncomfortable with Arc, they can
always opt out in two taps or clicks.

All that said, users are happy with Arc.

Arc has over 100 million users around the world, from every country
(including disadvantaged countries), and only 0.4% of users have elected
to opt out.

**Comment by spirillen** [comment]
Where is that opt-in(out) pop-up??

![image](https://user-images.githubusercontent.com/44526987/123704492-f6de6a80-d865-11eb-9b7a-818059d0831d.png)

**Comment by spirillen** [comment]
When this is said, I don't understand why anybody would allow you to profit on thers internet connection without proper payments for leasing of there lines.

**Comment by gruns** [comment]
> I don't see them.

Lower left corner:

![image](https://user-images.githubusercontent.com/1041265/123706809-9d524d80-d81d-11eb-9713-846b787f4238.png)

If the widget doesn't appear, my first guess is you have a custom rule in one of your filters that blocks the loading of https://arc.io/widget.min.js.

> Laptop connects via WI-FI or USB to mobile device, the laptop doesn't now whether the mobile device is on a metered connection or not, it's just yet another gateway ...

Combination of the Network Information API

  * https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation

and public lists of fixed vs cellular ISPs, eg Comcast (fixed) vs T-Mobile (cellular) in the United States.

> When this is said, I don't understand why anybody would allow you to profit on thers internet connection without proper payments for leasing of there lines.

Users opt in to support their favorite sites, from which they derive great value, without ads. Like Patreon. Running a website isn't free, and many users understand that and cherish the ability Arc gives them to support the sites they love in a manner that improves the site's performance, preserves their privacy, and doesn't interrupt the user experience with ads.

**Comment by spirillen** [comment]
> Running a website isn't free

Tell me about it, done it for ~20 years :smirk: (Just running mypdns.org cost something)

That's one other reason to why I hate ads/tracking/spying. I have proven it isn't necessary, it's just buzz and violating most countries laws (why the 1/0 version have slip through I don't understand)

> Combination of the Network Information **SpyWare** API

And you are doing what with these data once you have registered them?

And what are you doing when call to choose lists are blocked in firewalls?
