### ISSUE TITLE
aniwatch.me

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#7936]
![image](https://user-images.githubusercontent.com/84580704/119850328-1e17e400-bf16-11eb-9f94-57fa2bbded2d.png)

**Comment by spirillen** [comment]
First: I don't see any popup/notification

Second, The site is dead

![image](https://user-images.githubusercontent.com/44526987/120505406-3c258e80-c3c5-11eb-9a77-2e4617089920.png)

**Comment by IThinkIAmCool** [comment]
@spirillen ![image](https://user-images.githubusercontent.com/84580704/120525165-81a38500-c3e0-11eb-930b-9fe86a0cc1e2.png)

**Comment by spirillen** [comment]
> @spirillen ![image](https://user-images.githubusercontent.com/84580704/120525165-81a38500-c3e0-11eb-930b-9fe86a0cc1e2.png)

??

**Comment by IThinkIAmCool** [comment]
Have you clicked on the notification icon?

**Comment by spirillen** [comment]
> Have you clicked on the notification icon?

AAhhh now I can see what the image is :eyeglasses: 

It because I ofcurse have disabled all such things in my brower settings :laughing: 
![image](https://user-images.githubusercontent.com/44526987/120555742-ce488980-c3fb-11eb-81cb-27af3dc39aed.png)

All these are blocked FF + tor-FF :smirk: 

![image](https://user-images.githubusercontent.com/44526987/120555803-e4564a00-c3fb-11eb-8148-3e61f46498ef.png)
![image](https://user-images.githubusercontent.com/44526987/120555846-f33cfc80-c3fb-11eb-8fe2-678c598f885e.png)

**Comment by ryanbr** [comment]
Site is dead, closing.
