### ISSUE TITLE
(betting ad(s)) beermoneyforum.com

### ISSUE THREAD

**Issue by ghost** [easylist/easylist#7966]

**Comment by DandelionSprout** [comment]
This is a tricky one. Because, as much as I hate online casino ads recently, I struggle to determine which of the three gambling-related rows whose posts are organic or are disguised ads.

![image](https://user-images.githubusercontent.com/22780683/120398664-f2906180-c33a-11eb-8980-d5ef08ed3173.png)

The "Best casinos" row is at least certainly an ad, so I propose `beermoneyforum.com##.node--id157`

**Comment by ryanbr** [comment]
Looks fine here
