### ISSUE TITLE
yle.fi cookie banner

### ISSUE THREAD

**Issue by 07416** [easylist/easylist#8518]
### List the website(s) you're having issues:`

`https://yle.fi/`

### What happens?

a cookie banner covers the page:

![image](https://user-images.githubusercontent.com/14923168/127781130-4fe9d5d1-3eb9-4e65-a2f6-65497f79b0c2.png)

### Other details:

[Since the website doesn't appear to have any dedicated cookie-related entries on the Easylist](https://github.com/easylist/easylist/search?q=yle.fi), I've omitted my personal configuration.

**Comment by peace2000** [comment]
If that banner is blocked, embedded Twitter tweets can't be displayed https://yle.fi/uutiset/3-11972567

Social media cookies have to be accepted in order to see embedded tweets.

Though, tweets can be opened in a separate window but blocking that banner kinda breaks functionality... So it's a 50 % / 50 % call, do you hate the banner more or do you hate broken functionality?

**Comment by ryanbr** [comment]
Does using `||yle-consent-sdk.yle.fi^` cause any issues?

**Comment by 07416** [comment]
> Does using `||yle-consent-sdk.yle.fi^` cause any issues?

@ryanbr Breaks the Twitter embeds, also tested in Chromium `91.0.4472.164` with only uBlock Origin.

![image](https://user-images.githubusercontent.com/14923168/127865728-62f8741e-a413-4ee9-881e-5514eec705c9.png)

[content can't be displayed - verify social media cookie settings]

However, I'll personally use the said filter for now.

**Comment by krystian3w** [comment]
Maybe needed is snippet.

**Comment by peace2000** [comment]
Only in Adguard is possible to fix this, as it allows to use scripts to add cookies. No known fix for other blockers.

Imo, I'd probably keep the filter. Seeing the whole page cookie banner every time you visit the page is more annoying than the need to occasionally open tweets externally.

**Comment by krystian3w** [comment]
You try use `watch-attr` in uBo?

**Comment by peace2000** [comment]
Ok this will be imo reasonable filter `yle.fi###yle-consent-sdk-container:not(:has( ~ .yle__app a[href^="https://twitter.com/"]))` when browsers start to support CCS4 and `:has` natively. This filter I came up with, hides the banner only if the article doesn't contain embedded tweets. But it blinks so it will have to wait for CCS4...

**Comment by krystian3w** [comment]
uBO by bug also support:

`yle.fi###yle-consent-sdk-container:not(~ .yle__app a[href^="https://twitter.com/"])`

but AdGuard mark as invalid/omit.

**Comment by peace2000** [comment]
Made an improvement: instead of whitelisting according to specific href elements, it's better to whitelist according to error message:

`Sisältöä ei voida näyttää` - translation : `Content can't be shown`

As it's always possible there could be other embedded elements as well, not just Twitter related.

**Comment by 07416** [comment]
The banner has been modified (the issue returned recently), open any article on the frontpage `https://yle.fi/`

**Comment by peace2000** [comment]
https://yle.fi/uutiset/3-12278644 Still works for me. Are you sure your filters/lists are active and you don't have "disable cosmetic filtering" option enabled?

**Comment by krystian3w** [comment]
Or you don't use too old uBo or legacy version for older Firefox, palemoon/basilisk?

AdGuard still no fixed unhide nodes: https://github.com/AdguardTeam/ExtendedCss/issues/122
