### ISSUE TITLE
taiwanese pinkoi tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylist#8627]
https://www.pinkoi.com/

```
||pinkoi.com^$removeparam=/ref_.*/
```

**Comment by spirillen** [comment]
Suggesting this rule as well, not that I have any clue about (@Yuki2718, @c2xusnpq6 ) about what it says, but the CSS indicating spam to me

##.emergency-alert

![image](https://user-images.githubusercontent.com/44526987/129053016-ae43bfe1-2483-4e26-ad0f-e7525653e1e2.png)

**Comment by spirillen** [comment]
> Why you open an removeparam issue in EL? Better to open in AdGuard repo.

Cos I can't work with people who's [moral is for sale](https://adguard.com/en/blog/ad_formats_rated_and_ranked.html) for a few bucks :dollar: that's why I work with Free Open Source, Also one of the reason I do not remove "breakable" domains from my list. I'm not to determine who should be allowed to track/spy on anyone not ever not for gold.

The only judge for this is the end-users by them self, based on knowledge of the consequence.

**Comment by Yuki2718** [comment]
I talked to @c2xusnpq6 and the reason is EL does not address removeparam issue as this is an advanced feature of AG/uBO.

**Comment by c2xusnpq6** [comment]
@Yuki2718 `$queryprune` ? 🤔
