### ISSUE TITLE
[NSFW] https://www.sunporno.com (popunder)

### ISSUE THREAD

**Issue by CbumDino** [easylist/easylist#9516]
### List the website(s) you're having issues:

https://www.sunporno.com

### What happens?

Popunders after clicking in any content at the beginning

### List Subscriptions you're using:

ABP filters
EasyList Spanish+EasyList

### Your settings

- OS/version: macOS Catalina 10.15.7
- Browser/version: Chrome 95
- Adblock Extension/version: ABP 3.11.2

### Other details:
Proposed filter: ||frms.fuckandcdn.com^

<img width="1439" alt="Screenshot 2021-10-28 at 12 37 50" src="https://user-images.githubusercontent.com/65717387/139292934-ec094ee0-da4c-444b-8974-0d8960846473.png">
<img width="1437" alt="Screenshot 2021-10-28 at 12 34 26" src="https://user-images.githubusercontent.com/65717387/139292945-f4a35c52-b4af-4fb0-9fbd-9038b20b4d0e.png">

**Comment by stephenhawk8054** [comment]
There's an ad frame at the top right of website.

URL: `https://www.sunporno.com/videos/956452/amateur-babe-drilled-for-a-free-cab-fare`

[NSFW screenshot](https://i.ibb.co/P9PPsPD/image.png)

Firefox 94.0.1. ublock 1.38.6 default settings.

It's caused by this script: `https://www.sunporno.com/abl.php`
Proposed filter:

`||sunporno.com/abl.php$script`
