### ISSUE TITLE
freebitz.xyz

### ISSUE THREAD

**Issue by stephenhawk8054** [easylist/easylist#9868]
### List the website(s) you're having issues:
`https://freebitz.xyz/autofaucet`

### What happens?
Ads placeholders

### List Subscriptions you're using:
ublock default

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox 94.0.2
- Adblock Extension/version: ublock 1.39.0

### Other details:
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/143666178-efa39f38-e0f3-4c27-ad73-e46e368224e1.png)

</details>

Proposed filter:

`freebitz.xyz##[class*="Banner"]`

**Comment by spirillen** [comment]
Well this one mate me play a bit with the site and I came up with these rules from the page-source:

```css
freebitz.xyz##div[class^="Banner"]
freebitz.xyz##div[class^="chatbro_"]
freebitz.xyz##div[class^="hilltopads"]
freebitz.xyz##div[class^="optiads"]
freebitz.xyz##div[class^="propeller"]
```

Of these rules i found this one as the needed as the othe one is covered by other rules like
```css
/728x90_
/160x600_
```

```css
freebitz.xyz##div[class^="Banner"]
```

This leaves me with the question @ryanbr, why did you chose to make 3 rules like:

https://github.com/easylist/easylist/commit/2c823fb67735fb0fa877d9bd5415e041fef0252f#diff-d95e1ad0368a5fb3bacb89fc7f209b9fa33a9974d9d2cf4b9a98903b7aa356a2R653-R655

rather than one by using the class rule?

**Comment by edivaniadc** [comment]
@ryanbr I've seen popup placeholders on the top and bottom.

Proposed filter:`freebitz.xyz###orquidea-slideup`

<img width="1236" alt="plh" src="https://user-images.githubusercontent.com/57706597/143852662-f286ed2a-98b9-4484-a3f3-da9a7b5f2879.png">
