### ISSUE TITLE
rateyourmusic.com

### ISSUE THREAD

**Issue by jmsfilipe** [easylist/easylist#9957]
### List the website(s) you're having issues:

https://rateyourmusic.com/
https://www.blabbermouth.net/news/ted-nugent-says-he-couldnt-have-a-meaningful-conversation-with-david-lee-roth-the-guy-was-out-of-his-mind/
https://www.cifraclub.com.br/marilia-mendonca/de-quem--a-culpa/
https://www.songfacts.com/facts/burl-ives/holly-jolly-christmas

### What happens?

The "Play" button gets blocked, because the URL `https://partner.linkfire.com/channel_partners/script.js` is blocked.
At Linkfire, we've made several changes to that script, so that it no longer includes any ad related code. Hopefully, this will help you guys reconsider whitelisting it. Let me know in what other ways could we improve.

<img width="413" alt="Screenshot 2021-12-06 at 21 55 33" src="https://user-images.githubusercontent.com/9056469/144921245-08f072c0-4f6c-4436-ae14-462c8edfc776.png">

### List Subscriptions you're using:

AdBlock

### Your settings

- OS/version: MacOS Monterey
- Browser/version: Chrome 96
- Adblock Extension/version: 4.40

**Comment by ryanbr** [comment]
Isn't this just ads for various music services? regardless of the play button. @jmsfilipe

**Comment by sra135** [comment]
@ryanbr The goal of the play button is to enable music discovery for users of music related website. The intent of it is not to advertise a set list of services but is much more customised than that. It is enabling users to find relevant services in their country and leads them to the exact artist/album/track they wish to listen to, and not to a sign up page.

**Comment by jmsfilipe** [comment]
@ryanbr What @sra135 said. We perceive this not as an ad, instead as a way for the users to actually listen to song in whatever service they prefer.

**Comment by ryanbr** [comment]
It is viewed as an advert for various music services.

**Comment by ryanbr** [comment]
Literally called an advert, when it's allowed; ![songfacts](https://user-images.githubusercontent.com/1659004/145202586-a8611bc6-f158-444b-a107-9e3593db7485.png)

**Comment by jmsfilipe** [comment]
@ryanbr 

While that’s true that for songfacts it shows ‘Ad’, the button is definitely way more than that -  if you click it, it actually plays a proper 30second sample of the music.

I understand there are arguments for both points of view. But in our perspective, the behaviour and functionally provided by the button differentiates it enough from any typical ad you see on the internet.

Specifically concerning RYM, being a music discovery platform, this unit plays an essential part in the experience so that the user can actually listen to the song in the desired service.

The unit itself might show ads in some cases, but that code is loaded from different scripts. We’re wondering, is there a way we could reach a compromise where the ad scripts are blocked (I can provide that), but `https://partner.linkfire.com/channel_partners/script.js` isn’t?

**Comment by sonemic** [comment]
It is inaccurate to call this an "advert for various music services". As I explained in https://github.com/easylist/easylist/issues/9731, it's a unit which *can* contain ads or affiliate links, but any ads/links it would contain are already blocked by other filters, so blocking it entirely does nothing but remove core site functionality. 

Rateyourmusic.com is a music encyclopedia/database. For each album, there is a section where users of the site themselves can submit and vote on which albums appear on which streaming services, along with the relevant URL to directly access that album on the service. This data then appears in the Linkfire unit so that people can directly access/stream the album from the site.

As of 1 December, 901,050 such links have been submitted by users. The five main services we support are Spotify, Bandcamp, Apple Music, Soundcloud and Youtube. The distribution of links submitted are as follows:

Spotify: 343,642
Bandcamp: 245,594
Apple Music: 135,970
YouTube: 113,474
SoundCloud: 62,370

We receive *zero* revenue and have *zero* commercial affiliation whatsoever with Spotify, Bandcamp, Soundcloud and YouTube, which represent the vast majority of links submitted (and actual usage) of the feature. With Apple Music, if a user submits a link, we add an affiliate code to the end, because there is literally no downside to doing so from our end. 

Linkfire places a CPM ad inside the unit and can add additional affiliate links to the unit. Again, the CPM ad is already blocked, and affiliate links are already blocked by numerous adblock filter lists.

The streaming links feature was obviously not designed with commercial promotion in mind, given that it was designed transparently with direct consultation with our users and mostly promotes services for which we have no commercial relationship and receive no revenue.

Your previous comment in https://github.com/easylist/easylist/issues/9731 was "Cleanup/Remove the adcode, which why its in EL" and we followed this advice; the ad code is now removed. Hopefully we can work out a solution so that this feature is no longer blocked for our users.

**Comment by ryanbr** [comment]
Remove the tracking (fingerprinting/UA/ bits) from the script also.


Still in use: "Not an advert", yet use Ad labels in the JS. The trust is pretty low here
```
showAdTime
remainingAdTime
showAdLabel
showFallbackAd
```

**Comment by jmsfilipe** [comment]
Hi @ryanbr 

We did some more cleanup on our side, the script doesn't contain any more of the labels you mentioned.

Are we in a good position now?

**Comment by ryanbr** [comment]
I haven't checked the script, I hope you're not just renaming the labels and actually removing this code. @jmsfilipe

**Comment by jmsfilipe** [comment]
@ryanbr We completely removed the `showAdLabel` behaviour
As for the others, their behaviour has been adjusted and renamed. None of that code will be triggered, since as @sonemic pointed out, the CPM ads are already blocked by several lists.
